<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 Exploratory spatial data analysis | GEOG0114: Principles of Spatial Analysis</title>
  <meta name="description" content="GEOG114: Principles of Spatial Analysis handbook." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="5 Exploratory spatial data analysis | GEOG0114: Principles of Spatial Analysis" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://jtvandijk.github.io/GEOG0114/" />
  
  <meta property="og:description" content="GEOG114: Principles of Spatial Analysis handbook." />
  <meta name="github-repo" content="jtvandijk/GEOG0114" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 Exploratory spatial data analysis | GEOG0114: Principles of Spatial Analysis" />
  
  <meta name="twitter:description" content="GEOG114: Principles of Spatial Analysis handbook." />
  

<meta name="author" content="Justin van Dijk and Joanna Wilkin" />


<meta name="date" content="2020-11-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="spatial-autocorrelation.html"/>
<link rel="next" href="point-pattern-analysis.html"/>
<script src="libs/header-attrs-2.3/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/vembedr-0.1.4/css/vembedr.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="assets/custom.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo">
<a href="https://www.ucl.ac.uk/module-catalogue/modules/principles-of-spatial-analysis-GEOG0114"><img src="images/general/ucl_logo.png">
</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#get-in-touch"><i class="fa fa-check"></i>Get in touch</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#noticed-a-mistake-in-this-resource"><i class="fa fa-check"></i>Noticed a mistake in this resource?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="course-information.html"><a href="course-information.html"><i class="fa fa-check"></i>Course information</a>
<ul>
<li class="chapter" data-level="" data-path="course-information.html"><a href="course-information.html#module-structure"><i class="fa fa-check"></i>Module structure</a></li>
<li class="chapter" data-level="" data-path="course-information.html"><a href="course-information.html#weekly-topics"><i class="fa fa-check"></i>Weekly topics</a></li>
<li class="chapter" data-level="" data-path="course-information.html"><a href="course-information.html#learning-objectives"><i class="fa fa-check"></i>Learning objectives</a></li>
<li class="chapter" data-level="" data-path="course-information.html"><a href="course-information.html#reading-list"><i class="fa fa-check"></i>Reading list</a></li>
<li class="chapter" data-level="" data-path="course-information.html"><a href="course-information.html#module-assessment-details"><i class="fa fa-check"></i>Module assessment details</a></li>
<li class="chapter" data-level="" data-path="course-information.html"><a href="course-information.html#useful-additional-resources"><i class="fa fa-check"></i>Useful additional resources</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="spatial-analysis-for-data-science.html"><a href="spatial-analysis-for-data-science.html"><i class="fa fa-check"></i><b>1</b> Spatial analysis for data science</a></li>
<li class="chapter" data-level="2" data-path="geographical-representation.html"><a href="geographical-representation.html"><i class="fa fa-check"></i><b>2</b> Geographical representation</a></li>
<li class="chapter" data-level="3" data-path="spatial-properties-and-relationships.html"><a href="spatial-properties-and-relationships.html"><i class="fa fa-check"></i><b>3</b> Spatial properties and relationships</a></li>
<li class="chapter" data-level="4" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html"><i class="fa fa-check"></i><b>4</b> Spatial autocorrelation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#neighbours"><i class="fa fa-check"></i><b>4.1</b> Neighbours</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#setting-up-the-environment"><i class="fa fa-check"></i><b>4.1.1</b> Setting up the environment</a></li>
<li class="chapter" data-level="4.1.2" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#euclidean-neighbours"><i class="fa fa-check"></i><b>4.1.2</b> Euclidean neighbours</a></li>
<li class="chapter" data-level="4.1.3" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#shared-boundary-neighbours"><i class="fa fa-check"></i><b>4.1.3</b> Shared boundary neighbours</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#quantifying-difference-over-space"><i class="fa fa-check"></i><b>4.2</b> Quantifying difference over space</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#our-property-is-theft."><i class="fa fa-check"></i><b>4.2.1</b> Our property is theft.</a></li>
<li class="chapter" data-level="4.2.2" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#global-morans-i"><i class="fa fa-check"></i><b>4.2.2</b> Global Moran’s I</a></li>
<li class="chapter" data-level="4.2.3" data-path="spatial-autocorrelation.html"><a href="spatial-autocorrelation.html#local-morans-i"><i class="fa fa-check"></i><b>4.2.3</b> Local Moran’s I</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="exploratory-spatial-data-analysis.html"><a href="exploratory-spatial-data-analysis.html"><i class="fa fa-check"></i><b>5</b> Exploratory spatial data analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="exploratory-spatial-data-analysis.html"><a href="exploratory-spatial-data-analysis.html#introduction_w05"><i class="fa fa-check"></i><b>5.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="exploratory-spatial-data-analysis.html"><a href="exploratory-spatial-data-analysis.html#overview_w05"><i class="fa fa-check"></i><b>5.1.1</b> Video: Overview</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="exploratory-spatial-data-analysis.html"><a href="exploratory-spatial-data-analysis.html#tidy-data"><i class="fa fa-check"></i><b>5.2</b> Tidy data</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="exploratory-spatial-data-analysis.html"><a href="exploratory-spatial-data-analysis.html#video-tidy-data"><i class="fa fa-check"></i><b>5.2.1</b> Video: Tidy data</a></li>
<li class="chapter" data-level="5.2.2" data-path="exploratory-spatial-data-analysis.html"><a href="exploratory-spatial-data-analysis.html#what-do-tidy-data-look-like"><i class="fa fa-check"></i><b>5.2.2</b> What do tidy data look like?</a></li>
<li class="chapter" data-level="5.2.3" data-path="exploratory-spatial-data-analysis.html"><a href="exploratory-spatial-data-analysis.html#example-creating-tidy-data"><i class="fa fa-check"></i><b>5.2.3</b> Example: Creating tidy data</a></li>
<li class="chapter" data-level="5.2.4" data-path="exploratory-spatial-data-analysis.html"><a href="exploratory-spatial-data-analysis.html#assignment_w05"><i class="fa fa-check"></i><b>5.2.4</b> Assignments</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="exploratory-spatial-data-analysis.html"><a href="exploratory-spatial-data-analysis.html#exploratory-spatial-data-analysis-in-r"><i class="fa fa-check"></i><b>5.3</b> Exploratory spatial data analysis in R</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="exploratory-spatial-data-analysis.html"><a href="exploratory-spatial-data-analysis.html#video-exploratory-spatial-data-analysis"><i class="fa fa-check"></i><b>5.3.1</b> Video: Exploratory spatial data analysis</a></li>
<li class="chapter" data-level="5.3.2" data-path="exploratory-spatial-data-analysis.html"><a href="exploratory-spatial-data-analysis.html#example-exploring-our-dataset"><i class="fa fa-check"></i><b>5.3.2</b> Example: Exploring our dataset</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="exploratory-spatial-data-analysis.html"><a href="exploratory-spatial-data-analysis.html#spatial-heterogeneity"><i class="fa fa-check"></i><b>5.4</b> Spatial heterogeneity</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="exploratory-spatial-data-analysis.html"><a href="exploratory-spatial-data-analysis.html#video-spatial-heterogeneity"><i class="fa fa-check"></i><b>5.4.1</b> Video: Spatial heterogeneity</a></li>
<li class="chapter" data-level="5.4.2" data-path="exploratory-spatial-data-analysis.html"><a href="exploratory-spatial-data-analysis.html#example-accounting-for-spatial-heterogeneity"><i class="fa fa-check"></i><b>5.4.2</b> Example: Accounting for spatial heterogeneity</a></li>
<li class="chapter" data-level="" data-path="exploratory-spatial-data-analysis.html"><a href="exploratory-spatial-data-analysis.html#geographically-weighted-regression"><i class="fa fa-check"></i>Geographically Weighted Regression</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="exploratory-spatial-data-analysis.html"><a href="exploratory-spatial-data-analysis.html#take-home-message"><i class="fa fa-check"></i><b>5.5</b> Take home message</a></li>
<li class="chapter" data-level="5.6" data-path="exploratory-spatial-data-analysis.html"><a href="exploratory-spatial-data-analysis.html#attributions_w05"><i class="fa fa-check"></i><b>5.6</b> Attributions</a></li>
<li class="chapter" data-level="5.7" data-path="exploratory-spatial-data-analysis.html"><a href="exploratory-spatial-data-analysis.html#feedback_w05"><i class="fa fa-check"></i><b>5.7</b> Feedback</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="point-pattern-analysis.html"><a href="point-pattern-analysis.html"><i class="fa fa-check"></i><b>6</b> Point pattern analysis</a>
<ul>
<li class="chapter" data-level="6.1" data-path="point-pattern-analysis.html"><a href="point-pattern-analysis.html#feedback_w06"><i class="fa fa-check"></i><b>6.1</b> Feedback</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="geostatistics.html"><a href="geostatistics.html"><i class="fa fa-check"></i><b>7</b> Geostatistics</a>
<ul>
<li class="chapter" data-level="7.1" data-path="geostatistics.html"><a href="geostatistics.html#feedback_w07"><i class="fa fa-check"></i><b>7.1</b> Feedback</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="cluster-analysis.html"><a href="cluster-analysis.html"><i class="fa fa-check"></i><b>8</b> Cluster analysis</a>
<ul>
<li class="chapter" data-level="8.1" data-path="cluster-analysis.html"><a href="cluster-analysis.html#feedback_w08"><i class="fa fa-check"></i><b>8.1</b> Feedback</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="bayesian-modelling.html"><a href="bayesian-modelling.html"><i class="fa fa-check"></i><b>9</b> Bayesian modelling</a></li>
<li class="chapter" data-level="10" data-path="reproducible-research.html"><a href="reproducible-research.html"><i class="fa fa-check"></i><b>10</b> Reproducible research</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GEOG0114: Principles of Spatial Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="exploratory-spatial-data-analysis" class="section level1" number="5">
<h1><span class="header-section-number">5</span> Exploratory spatial data analysis</h1>
<div id="introduction_w05" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Introduction</h2>
<p>This week, we focus on the second of the two key properties of spatial data: spatial heterogeneity. With the underlying process (or processes) that govern a spatial variable likely to vary across space, a single global relationship for an entire region of study may not adequately model the process that governs outcomes in any given location of the study region. As a result, multiple methods have been developed to incorporate ‘space’ into traditional regression models, including spatial lag models, spatial error models, and Geographical Weighted Regression.</p>
<p>This week provides the building blocks to conducting a statistical and spatial investigation into the relationships between spatial variables, looking at the concept of <strong>Exploratory Spatial Data Analysis (ESDA)</strong>. We then look at the two of the three types of spatial regression models in turn to understand their methodology and potential advantages and limitations in accounting for space when modelling relationships. However, before we move on to ESDA, we will look into some aspects of data preparation, data cleaning, and creating a <strong>tidy dataset</strong>.</p>
<p>In the first part of this week’s session we will start by creating a <strong>tidy dataset</strong> using some data from the <a href="https://www.ons.gov.uk/census/2011census">UK 2011 Census of Population</a>. In the second part of this week’s session we will explore potential factors that may contribute to bicycle theft in London. We conduct an ESDA of these variables, followed by statistical and spatial regression analysis to determine whether our variables contribute to bicycle theft in our area of study.</p>
<p>This week is structured by <strong>three</strong> short lecture videos, <strong>two</strong> <a href="exploratory-spatial-data-analysis.html#assignment_w05">assignments</a> that you need to do in preparation for Friday’s seminar, and the practical material. As always, this <a href="https://rl.talis.com/3/ucl/lists/3FB0C66A-F603-A402-A31C-28F2DA091AB6.html?lang=en-gb&amp;login=1">week’s reading list</a> is available on the UCL library reading list page for the course.</p>
<p><strong>Please be aware that you will need to [submit the result[#submit_w05] of the second assignment before Friday morning 09h00 UK time (GMT+0).</strong></p>
<div id="overview_w05" class="section level3" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> Video: Overview</h3>
<p><div class="vembedr" align="left">
<div>
<iframe src="https://web.microsoftstream.com/embed/video/9ba75497-60e1-40c2-99c4-ac6057acbd27?autoplay=false&amp;showinfo=true" width="533" height="300" style="border:none;"></iframe>
</div>
</div>
[Lecture slides] <a href="https://web.microsoftstream.com/video/9ba75497-60e1-40c2-99c4-ac6057acbd27?list=studio">[Watch on MS stream]</a></p>
</div>
</div>
<div id="tidy-data" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Tidy data</h2>
<p>Over the past weeks a lot of information has come your way, diving deep into the world of Spatial Data Science. However, whilst you are slowly becoming proficient in using R and Python to solve complex (spatial) problems, it is now a good moment to start thinking about data themselves and how they are organised. This is crucial for when you are moving on to working on your own projects where you have to source data yourselves: the vast majority of the data you will find in the public domain (or private domain for that matter) will be <strong>dirty data</strong>. With dirty data we mean data that needs some form of pre-processing, cleaning, and linkage before you can use it for your analysis. Exploratory Spatial Data Analysis very much starts with your data preparation .</p>
<p>In the following, you will learn a consistent way to structure your data in R: <strong>tidy data</strong>. Tidy data, as formalised by <a href="http://hadley.nz/">R Wizard Hadley Wickham</a> in his contribution to the <a href="http://www.jstatsoft.org/v59/i10/paper">Journal of Statistical Software</a> is not only very much at the core of the <code>tidyverse</code> R package, but also of general importance when organising your data. In the words, of <a href="https://r4ds.had.co.nz/tidy-data.html">the Wizard</a>:</p>
<blockquote>
<p>Once you have tidy data and the tidy tools provided by packages in the tidyverse, you will spend much less time munging data from one representation to another, allowing you to spend more time on the analytic questions at hand.</p>
</blockquote>
<div id="video-tidy-data" class="section level3" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Video: Tidy data</h3>
<p><div class="vembedr" align="left">
<div>
<iframe src="https://web.microsoftstream.com/embed/video/ae00eeb4-4558-4f95-8e26-9a16d970bbd1?autoplay=false&amp;showinfo=true" width="533" height="300" style="border:none;"></iframe>
</div>
</div>
<a href="https://github.com/jtvandijk/GEOG0114/tree/master/slides/w05/w05_01_tidy_data.pdf">[Lecture slides]</a> <a href="https://web.microsoftstream.com/video/ae00eeb4-4558-4f95-8e26-9a16d970bbd1?list=studio">[Watch on MS stream]</a></p>
</div>
<div id="what-do-tidy-data-look-like" class="section level3" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> What do tidy data look like?</h3>
<p>You can represent the same underlying data in multiple ways. The example below, taken from the the <code>tidyverse</code> package and described in the <a href="https://r4ds.had.co.nz/tidy-data.html">R for Data Science</a> book, shows that the same data can organised in four different ways.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="exploratory-spatial-data-analysis.html#cb66-1" aria-hidden="true"></a><span class="co"># load the tidyverse </span></span>
<span id="cb66-2"><a href="exploratory-spatial-data-analysis.html#cb66-2" aria-hidden="true"></a><span class="kw">library</span>(tidyverse)</span></code></pre></div>
<p>Table <strong>1</strong>:</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="exploratory-spatial-data-analysis.html#cb67-1" aria-hidden="true"></a>table1</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   country      year  cases population
##   &lt;chr&gt;       &lt;int&gt;  &lt;int&gt;      &lt;int&gt;
## 1 Afghanistan  1999    745   19987071
## 2 Afghanistan  2000   2666   20595360
## 3 Brazil       1999  37737  172006362
## 4 Brazil       2000  80488  174504898
## 5 China        1999 212258 1272915272
## 6 China        2000 213766 1280428583</code></pre>
<p>Table <strong>2</strong>:</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="exploratory-spatial-data-analysis.html#cb69-1" aria-hidden="true"></a>table2</span></code></pre></div>
<pre><code>## # A tibble: 12 x 4
##    country      year type            count
##    &lt;chr&gt;       &lt;int&gt; &lt;chr&gt;           &lt;int&gt;
##  1 Afghanistan  1999 cases             745
##  2 Afghanistan  1999 population   19987071
##  3 Afghanistan  2000 cases            2666
##  4 Afghanistan  2000 population   20595360
##  5 Brazil       1999 cases           37737
##  6 Brazil       1999 population  172006362
##  7 Brazil       2000 cases           80488
##  8 Brazil       2000 population  174504898
##  9 China        1999 cases          212258
## 10 China        1999 population 1272915272
## 11 China        2000 cases          213766
## 12 China        2000 population 1280428583</code></pre>
<p>Table <strong>3</strong>:</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="exploratory-spatial-data-analysis.html#cb71-1" aria-hidden="true"></a>table3</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   country      year rate             
## * &lt;chr&gt;       &lt;int&gt; &lt;chr&gt;            
## 1 Afghanistan  1999 745/19987071     
## 2 Afghanistan  2000 2666/20595360    
## 3 Brazil       1999 37737/172006362  
## 4 Brazil       2000 80488/174504898  
## 5 China        1999 212258/1272915272
## 6 China        2000 213766/1280428583</code></pre>
<p>Table <strong>4a</strong>:</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="exploratory-spatial-data-analysis.html#cb73-1" aria-hidden="true"></a>table4a</span></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   country     `1999` `2000`
## * &lt;chr&gt;        &lt;int&gt;  &lt;int&gt;
## 1 Afghanistan    745   2666
## 2 Brazil       37737  80488
## 3 China       212258 213766</code></pre>
<p>Table <strong>4b</strong>:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="exploratory-spatial-data-analysis.html#cb75-1" aria-hidden="true"></a>table4b</span></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   country         `1999`     `2000`
## * &lt;chr&gt;            &lt;int&gt;      &lt;int&gt;
## 1 Afghanistan   19987071   20595360
## 2 Brazil       172006362  174504898
## 3 China       1272915272 1280428583</code></pre>
<p>None of these representations are wrong per se, however, not are equally easy to use. Only Table <strong>1</strong> can be considered as tidy data because it is the only table that adheres to the three rules that make a dataset tidy:</p>
<ol style="list-style-type: decimal">
<li>Each variable must have its own column.</li>
<li>Each observation must have its own row.</li>
<li>Each value must have its own cell.</li>
</ol>
<div class="figure" style="text-align: center"><span id="fig:05-figure-hadley-wickham"></span>
<img src="images/week05/05_a_tidy_data.png" alt="A visual representation of tidy data by [Hadley Wickham](https://r4ds.had.co.nz/tidy-data.html)." width="960" />
<p class="caption">
Figure 5.1: A visual representation of tidy data by <a href="https://r4ds.had.co.nz/tidy-data.html">Hadley Wickham</a>.
</p>
</div>
<p>Fortunately, there are some functions in the <code>tidyr</code> and <code>dplyr</code> packages, both part of the <code>tidyverse</code> that will help us cleaning and preparing our datasets to create a <strong>tidy dataset</strong>. The most important and useful functions are:</p>
<table>
<thead>
<tr class="header">
<th align="left">Package</th>
<th align="left">Function</th>
<th align="left">Use to</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">dplyr</td>
<td align="left">select</td>
<td align="left">select columns</td>
</tr>
<tr class="even">
<td align="left">dplyr</td>
<td align="left">filter</td>
<td align="left">select rows</td>
</tr>
<tr class="odd">
<td align="left">dplyr</td>
<td align="left">mutate</td>
<td align="left">transform or recode variables</td>
</tr>
<tr class="even">
<td align="left">dplyr</td>
<td align="left">summarise</td>
<td align="left">summarise data</td>
</tr>
<tr class="odd">
<td align="left">dplyr</td>
<td align="left">group by</td>
<td align="left">group data into subgropus for further processing</td>
</tr>
<tr class="even">
<td align="left">tidyr</td>
<td align="left">pivot_longer</td>
<td align="left">convert data from wide format to long format</td>
</tr>
<tr class="odd">
<td align="left">tidyr</td>
<td align="left">pivot_wider</td>
<td align="left">convert long format dataset to wide format</td>
</tr>
</tbody>
</table>
<blockquote>
<p>Remember that when you encounter a function in a piece of R code that you have not seen before and you are wondering what it does that you can get access the documentation through <code>?name_of_function</code>, e.g. <code>?pivot_longer</code>. For almost any R package, the documentation contains a list of arguments that the function takes, in which format the functions expects these arguments, as well as a set of usage examples.</p>
</blockquote>
</div>
<div id="example-creating-tidy-data" class="section level3" number="5.2.3">
<h3><span class="header-section-number">5.2.3</span> Example: Creating tidy data</h3>
<p>Now we know what consitute <strong>tidy data</strong>, we can put this into practice with an example using some data from the <a href="https://www.ons.gov.uk/">Office for National Statistics</a>. Let’s say we are asked by our bosses to analyse some data on the ethnic background of the UK population, for instance, because we want to get some insights into the relationship between <a href="https://www.theguardian.com/world/2020/oct/09/bame-groups-hit-hard-again-covid-second-wave-grips-uk-nations">COVID-19 and ethnic background</a>. Our assignment is to calculate the relative proportions of each ethnic group within the administrative geography of the <a href="https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/middlesuperoutputareamidyearpopulationestimates">Middle layer Super Output Area (MSOA)</a>. In order to do this, we have been given a file that contains data on ethnicity by age group at the MSOA-level of every person in the 2011 UK Census who is 16 year or older. Download the file to your own computer and <a href="spatial-autocorrelation.html#setting-up-the-environment">set up your data directory</a> in the same fashion as you did last week. You can also decide on setting up your own folder structure, no problem, just make sure that you update the file paths in the practical to match the file paths on your own computer.</p>
<blockquote>
<p>Make sure that after downloading you first unzip the data, for instance, using <a href="https://www.7-zip.org/">7-Zip</a> on Windows or using <a href="https://theunarchiver.com/">The Unarchiver</a> on Mac OS.</p>
</blockquote>
<div id="file-download" class="section level4 unnumbered">
<h4>File download</h4>
<table>
<thead>
<tr class="header">
<th align="left">File</th>
<th align="left">Type</th>
<th align="left">Link</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Etnicity by age group 2011 Census of Population</td>
<td align="left"><code>csv</code></td>
<td align="left"><a href="https://github.com/jtvandijk/GEOG0114/tree/master/raw/zip/msoa_eth2011_ew_16plus.zip">Download</a></td>
</tr>
</tbody>
</table>
<p>We start by making sure our <code>tidyverse</code> is loaded into R and using the <code>read_csv()</code> function to read our <code>csv</code> file.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="exploratory-spatial-data-analysis.html#cb77-1" aria-hidden="true"></a><span class="co"># load the tidyverse </span></span>
<span id="cb77-2"><a href="exploratory-spatial-data-analysis.html#cb77-2" aria-hidden="true"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb77-3"><a href="exploratory-spatial-data-analysis.html#cb77-3" aria-hidden="true"></a></span>
<span id="cb77-4"><a href="exploratory-spatial-data-analysis.html#cb77-4" aria-hidden="true"></a><span class="co"># read data into dataframe</span></span>
<span id="cb77-5"><a href="exploratory-spatial-data-analysis.html#cb77-5" aria-hidden="true"></a>df &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&#39;raw/population/msoa_eth2011_ew_16plus.csv&#39;</span>)</span>
<span id="cb77-6"><a href="exploratory-spatial-data-analysis.html#cb77-6" aria-hidden="true"></a>  </span>
<span id="cb77-7"><a href="exploratory-spatial-data-analysis.html#cb77-7" aria-hidden="true"></a><span class="co"># inspect the dataframe: number of columns</span></span>
<span id="cb77-8"><a href="exploratory-spatial-data-analysis.html#cb77-8" aria-hidden="true"></a><span class="kw">ncol</span>(df)</span></code></pre></div>
<pre><code>## [1] 385</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="exploratory-spatial-data-analysis.html#cb79-1" aria-hidden="true"></a><span class="co"># inspect the dataframe: number of rows</span></span>
<span id="cb79-2"><a href="exploratory-spatial-data-analysis.html#cb79-2" aria-hidden="true"></a><span class="kw">nrow</span>(df)</span></code></pre></div>
<pre><code>## [1] 7201</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="exploratory-spatial-data-analysis.html#cb81-1" aria-hidden="true"></a><span class="co"># inspect the dataframe: sneak peak</span></span>
<span id="cb81-2"><a href="exploratory-spatial-data-analysis.html#cb81-2" aria-hidden="true"></a><span class="kw">print</span>(df, <span class="dt">n_extra=</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## # A tibble: 7,201 x 385
##    msoa11cd `Sex: All perso… `Sex: All perso… `Sex: All perso… `Sex: All perso…
##    &lt;chr&gt;               &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;
##  1 E020025…              215              206              204                0
##  2 E020025…              175              170              168                1
##  3 E020025…              140              128              128                0
##  4 E020025…              160              155              154                0
##  5 E020025…              132              130              130                0
##  6 E020025…              270              263              261                0
##  7 E020025…              124              119              117                0
##  8 E020025…              150              125              117                0
##  9 E020025…              178              166              159                0
## 10 E020025…              162              159              157                0
## # … with 7,191 more rows, and 380 more variables: `Sex: All persons; Age: Age
## #   16 to 17; Ethnic Group: White: Gypsy or Irish Traveller; measures:
## #   Value` &lt;dbl&gt;, `Sex: All persons; Age: Age 16 to 17; Ethnic Group: White:
## #   Other White; measures: Value` &lt;dbl&gt;, …</code></pre>
<p>Because the data are split out over multiple columns, it is clear that the data are not directly suitable to establish the proportion of each ethnic group within the population of each MSOA. Let’s inspect the names of the columns to get a better idea of the structure of our data set.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="exploratory-spatial-data-analysis.html#cb83-1" aria-hidden="true"></a><span class="co"># inspect the dataframe: column names</span></span>
<span id="cb83-2"><a href="exploratory-spatial-data-analysis.html#cb83-2" aria-hidden="true"></a><span class="kw">names</span>(df)</span></code></pre></div>
<pre><code>##  [1] &quot;msoa11cd&quot;                                                                                                                  
##  [2] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: All categories: Ethnic group; measures: Value&quot;                          
##  [3] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: White: Total; measures: Value&quot;                                          
##  [4] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: White: English/Welsh/Scottish/Northern Irish/British; measures: Value&quot;  
##  [5] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: White: Irish; measures: Value&quot;                                          
##  [6] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: White: Gypsy or Irish Traveller; measures: Value&quot;                       
##  [7] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: White: Other White; measures: Value&quot;                                    
##  [8] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: Mixed/multiple ethnic group: Total; measures: Value&quot;                    
##  [9] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: Mixed/multiple ethnic group: White and Black Caribbean; measures: Value&quot;
## [10] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: Mixed/multiple ethnic group: White and Black African; measures: Value&quot;  
## [11] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: Mixed/multiple ethnic group: White and Asian; measures: Value&quot;          
## [12] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: Mixed/multiple ethnic group: Other Mixed; measures: Value&quot;              
## [13] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: Asian/Asian British: Total; measures: Value&quot;                            
## [14] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: Asian/Asian British: Indian; measures: Value&quot;                           
## [15] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: Asian/Asian British: Pakistani; measures: Value&quot;                        
## [16] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: Asian/Asian British: Bangladeshi; measures: Value&quot;                      
## [17] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: Asian/Asian British: Chinese; measures: Value&quot;                          
## [18] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: Asian/Asian British: Other Asian; measures: Value&quot;                      
## [19] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: Black/African/Caribbean/Black British: Total; measures: Value&quot;          
## [20] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: Black/African/Caribbean/Black British: African; measures: Value&quot;        
## [21] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: Black/African/Caribbean/Black British: Caribbean; measures: Value&quot;      
## [22] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: Black/African/Caribbean/Black British: Other Black; measures: Value&quot;    
## [23] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: Other ethnic group: Total; measures: Value&quot;                             
## [24] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: Other ethnic group: Arab; measures: Value&quot;                              
## [25] &quot;Sex: All persons; Age: Age 16 to 17; Ethnic Group: Other ethnic group: Any other ethnic group; measures: Value&quot;            
## [26] &quot;Sex: All persons; Age: Age 18 to 19; Ethnic Group: All categories: Ethnic group; measures: Value&quot;                          
## [27] &quot;Sex: All persons; Age: Age 18 to 19; Ethnic Group: White: Total; measures: Value&quot;                                          
## [28] &quot;Sex: All persons; Age: Age 18 to 19; Ethnic Group: White: English/Welsh/Scottish/Northern Irish/British; measures: Value&quot;  
## [29] &quot;Sex: All persons; Age: Age 18 to 19; Ethnic Group: White: Irish; measures: Value&quot;                                          
## [30] &quot;Sex: All persons; Age: Age 18 to 19; Ethnic Group: White: Gypsy or Irish Traveller; measures: Value&quot;                       
##  [ reached getOption(&quot;max.print&quot;) -- omitted 355 entries ]</code></pre>
<p>The column names are all awfully long and it looks like the data have been split out into age groups. Further to this, the data contain within group total counts: <em>all categories</em>, <em>white total</em>, <em>mixed/multiple ethnic group total</em>, and so on.</p>
<blockquote>
<p>You can also try using <code>View(df)</code> or use any other form of spreadsheet software (e.g. Microsoft Excel) to <strong>browse</strong> through the dataset to get a better idea of what is happening and get a better idea of the structure of the data. You first will need to understand the structure of your dataset before you can start reorganising your dataset.</p>
</blockquote>
<p>Although the data is messy and we will need to reorganise our data set, it does look there is some form of structure present that we can exploit: the various columns with population counts for each ethnic group are repeated for each of the different age groups. This means that we can go through the data frame in steps of equal size to select the data we want: starting from column 2 (column 1 only contains the reference to the adminsitrative geography) we want to select all 24 columns of data for that particular age group. We can create a <code>for</code> loop that does exactly that:</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="exploratory-spatial-data-analysis.html#cb85-1" aria-hidden="true"></a><span class="co"># loop through the columns of our data set</span></span>
<span id="cb85-2"><a href="exploratory-spatial-data-analysis.html#cb85-2" aria-hidden="true"></a><span class="cf">for</span> (column <span class="cf">in</span> <span class="kw">seq</span>(<span class="dv">2</span>,<span class="kw">ncol</span>(df),<span class="dv">24</span>)) {</span>
<span id="cb85-3"><a href="exploratory-spatial-data-analysis.html#cb85-3" aria-hidden="true"></a>    </span>
<span id="cb85-4"><a href="exploratory-spatial-data-analysis.html#cb85-4" aria-hidden="true"></a>  <span class="co"># index number of start column of age group</span></span>
<span id="cb85-5"><a href="exploratory-spatial-data-analysis.html#cb85-5" aria-hidden="true"></a>  start &lt;-<span class="st"> </span>column</span>
<span id="cb85-6"><a href="exploratory-spatial-data-analysis.html#cb85-6" aria-hidden="true"></a>  </span>
<span id="cb85-7"><a href="exploratory-spatial-data-analysis.html#cb85-7" aria-hidden="true"></a>  <span class="co"># index number of end column of age group</span></span>
<span id="cb85-8"><a href="exploratory-spatial-data-analysis.html#cb85-8" aria-hidden="true"></a>  stop &lt;-<span class="st"> </span>column <span class="op">+</span><span class="st"> </span><span class="dv">23</span> </span>
<span id="cb85-9"><a href="exploratory-spatial-data-analysis.html#cb85-9" aria-hidden="true"></a>  </span>
<span id="cb85-10"><a href="exploratory-spatial-data-analysis.html#cb85-10" aria-hidden="true"></a>  <span class="co"># print results</span></span>
<span id="cb85-11"><a href="exploratory-spatial-data-analysis.html#cb85-11" aria-hidden="true"></a>  <span class="kw">print</span>(<span class="kw">c</span>(start,stop))</span>
<span id="cb85-12"><a href="exploratory-spatial-data-analysis.html#cb85-12" aria-hidden="true"></a>}</span></code></pre></div>
<pre><code>## [1]  2 25
## [1] 26 49
## [1] 50 73
## [1] 74 97
## [1]  98 121
## [1] 122 145
## [1] 146 169
## [1] 170 193
## [1] 194 217
## [1] 218 241
## [1] 242 265
## [1] 266 289
## [1] 290 313
## [1] 314 337
## [1] 338 361
## [1] 362 385</code></pre>
<p>For each age group in our data, the printed values should <strong>(!)</strong> correspond with the index number of the start column of the age group and the index number of the end column of the age group, respectively. Let’s do a sanity check.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="exploratory-spatial-data-analysis.html#cb87-1" aria-hidden="true"></a><span class="co"># sanity check: age group 16-17 (start column)</span></span>
<span id="cb87-2"><a href="exploratory-spatial-data-analysis.html#cb87-2" aria-hidden="true"></a>df[,<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## # A tibble: 7,201 x 1
##    `Sex: All persons; Age: Age 16 to 17; Ethnic Group: All categories: Ethnic g…
##                                                                            &lt;dbl&gt;
##  1                                                                           215
##  2                                                                           175
##  3                                                                           140
##  4                                                                           160
##  5                                                                           132
##  6                                                                           270
##  7                                                                           124
##  8                                                                           150
##  9                                                                           178
## 10                                                                           162
## # … with 7,191 more rows</code></pre>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="exploratory-spatial-data-analysis.html#cb89-1" aria-hidden="true"></a><span class="co"># sanity check: age group 16-17 (end column)</span></span>
<span id="cb89-2"><a href="exploratory-spatial-data-analysis.html#cb89-2" aria-hidden="true"></a>df[,<span class="dv">25</span>]</span></code></pre></div>
<pre><code>## # A tibble: 7,201 x 1
##    `Sex: All persons; Age: Age 16 to 17; Ethnic Group: Other ethnic group: Any …
##                                                                            &lt;dbl&gt;
##  1                                                                             0
##  2                                                                             0
##  3                                                                             0
##  4                                                                             0
##  5                                                                             0
##  6                                                                             0
##  7                                                                             0
##  8                                                                             0
##  9                                                                             0
## 10                                                                             0
## # … with 7,191 more rows</code></pre>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="exploratory-spatial-data-analysis.html#cb91-1" aria-hidden="true"></a><span class="co"># sanity check: age group 18-19 (start column)</span></span>
<span id="cb91-2"><a href="exploratory-spatial-data-analysis.html#cb91-2" aria-hidden="true"></a>df[,<span class="dv">26</span>]</span></code></pre></div>
<pre><code>## # A tibble: 7,201 x 1
##    `Sex: All persons; Age: Age 18 to 19; Ethnic Group: All categories: Ethnic g…
##                                                                            &lt;dbl&gt;
##  1                                                                           157
##  2                                                                           129
##  3                                                                           102
##  4                                                                           162
##  5                                                                           121
##  6                                                                           217
##  7                                                                           126
##  8                                                                           231
##  9                                                                           175
## 10                                                                            95
## # … with 7,191 more rows</code></pre>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="exploratory-spatial-data-analysis.html#cb93-1" aria-hidden="true"></a><span class="co"># sanity check: age group 18-19 (end column)</span></span>
<span id="cb93-2"><a href="exploratory-spatial-data-analysis.html#cb93-2" aria-hidden="true"></a>df[,<span class="dv">49</span>]</span></code></pre></div>
<pre><code>## # A tibble: 7,201 x 1
##    `Sex: All persons; Age: Age 18 to 19; Ethnic Group: Other ethnic group: Any …
##                                                                            &lt;dbl&gt;
##  1                                                                             1
##  2                                                                             0
##  3                                                                             0
##  4                                                                             0
##  5                                                                             0
##  6                                                                             0
##  7                                                                             0
##  8                                                                             1
##  9                                                                             0
## 10                                                                             0
## # … with 7,191 more rows</code></pre>
<p>All seems to be correct and we have successfully identified our columns. This is great, however, we still cannot work with our data as everything is spread out over different columns. Let’s fix this by manipulating the shape of our data by turning columns into rows.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="exploratory-spatial-data-analysis.html#cb95-1" aria-hidden="true"></a><span class="co"># create function</span></span>
<span id="cb95-2"><a href="exploratory-spatial-data-analysis.html#cb95-2" aria-hidden="true"></a>columns_to_rows &lt;-<span class="st"> </span><span class="cf">function</span>(df, start, stop) {</span>
<span id="cb95-3"><a href="exploratory-spatial-data-analysis.html#cb95-3" aria-hidden="true"></a>  </span>
<span id="cb95-4"><a href="exploratory-spatial-data-analysis.html#cb95-4" aria-hidden="true"></a>  <span class="co"># columns we are interested in</span></span>
<span id="cb95-5"><a href="exploratory-spatial-data-analysis.html#cb95-5" aria-hidden="true"></a>  col_sub &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>,start<span class="op">:</span>stop)</span>
<span id="cb95-6"><a href="exploratory-spatial-data-analysis.html#cb95-6" aria-hidden="true"></a>  </span>
<span id="cb95-7"><a href="exploratory-spatial-data-analysis.html#cb95-7" aria-hidden="true"></a>  <span class="co"># subset the dataframe </span></span>
<span id="cb95-8"><a href="exploratory-spatial-data-analysis.html#cb95-8" aria-hidden="true"></a>  df_sub &lt;-<span class="st"> </span><span class="kw">select</span>(df,col_sub)</span>
<span id="cb95-9"><a href="exploratory-spatial-data-analysis.html#cb95-9" aria-hidden="true"></a>  </span>
<span id="cb95-10"><a href="exploratory-spatial-data-analysis.html#cb95-10" aria-hidden="true"></a>  <span class="co"># pivot the columns in the dataframe, exclude the MSOA code column </span></span>
<span id="cb95-11"><a href="exploratory-spatial-data-analysis.html#cb95-11" aria-hidden="true"></a>  df_piv &lt;-<span class="st"> </span><span class="kw">pivot_longer</span>(df_sub,<span class="op">-</span>msoa11cd)</span>
<span id="cb95-12"><a href="exploratory-spatial-data-analysis.html#cb95-12" aria-hidden="true"></a>  </span>
<span id="cb95-13"><a href="exploratory-spatial-data-analysis.html#cb95-13" aria-hidden="true"></a>  <span class="co"># rename columns</span></span>
<span id="cb95-14"><a href="exploratory-spatial-data-analysis.html#cb95-14" aria-hidden="true"></a>  <span class="kw">names</span>(df_piv) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;msoa11cd&#39;</span>,<span class="st">&#39;age_group&#39;</span>,<span class="st">&#39;count&#39;</span>)</span>
<span id="cb95-15"><a href="exploratory-spatial-data-analysis.html#cb95-15" aria-hidden="true"></a>  <span class="kw">return</span>(df_piv)</span>
<span id="cb95-16"><a href="exploratory-spatial-data-analysis.html#cb95-16" aria-hidden="true"></a>}</span>
<span id="cb95-17"><a href="exploratory-spatial-data-analysis.html#cb95-17" aria-hidden="true"></a></span>
<span id="cb95-18"><a href="exploratory-spatial-data-analysis.html#cb95-18" aria-hidden="true"></a><span class="co"># test</span></span>
<span id="cb95-19"><a href="exploratory-spatial-data-analysis.html#cb95-19" aria-hidden="true"></a><span class="kw">columns_to_rows</span>(df,<span class="dv">2</span>,<span class="dv">25</span>)</span></code></pre></div>
<pre><code>## # A tibble: 172,824 x 3
##    msoa11cd  age_group                                                     count
##    &lt;chr&gt;     &lt;chr&gt;                                                         &lt;dbl&gt;
##  1 E02002559 Sex: All persons; Age: Age 16 to 17; Ethnic Group: All categ…   215
##  2 E02002559 Sex: All persons; Age: Age 16 to 17; Ethnic Group: White: To…   206
##  3 E02002559 Sex: All persons; Age: Age 16 to 17; Ethnic Group: White: En…   204
##  4 E02002559 Sex: All persons; Age: Age 16 to 17; Ethnic Group: White: Ir…     0
##  5 E02002559 Sex: All persons; Age: Age 16 to 17; Ethnic Group: White: Gy…     2
##  6 E02002559 Sex: All persons; Age: Age 16 to 17; Ethnic Group: White: Ot…     0
##  7 E02002559 Sex: All persons; Age: Age 16 to 17; Ethnic Group: Mixed/mul…     4
##  8 E02002559 Sex: All persons; Age: Age 16 to 17; Ethnic Group: Mixed/mul…     1
##  9 E02002559 Sex: All persons; Age: Age 16 to 17; Ethnic Group: Mixed/mul…     2
## 10 E02002559 Sex: All persons; Age: Age 16 to 17; Ethnic Group: Mixed/mul…     1
## # … with 172,814 more rows</code></pre>
<p>This looks much better. Now let’s combine our loop with our newly created function to apply this to all of our data.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="exploratory-spatial-data-analysis.html#cb97-1" aria-hidden="true"></a><span class="co"># create an empty list to store our result from the loop</span></span>
<span id="cb97-2"><a href="exploratory-spatial-data-analysis.html#cb97-2" aria-hidden="true"></a>df_lst &lt;-<span class="st"> </span><span class="kw">list</span>()</span>
<span id="cb97-3"><a href="exploratory-spatial-data-analysis.html#cb97-3" aria-hidden="true"></a></span>
<span id="cb97-4"><a href="exploratory-spatial-data-analysis.html#cb97-4" aria-hidden="true"></a><span class="co"># loop through the columns of our data set</span></span>
<span id="cb97-5"><a href="exploratory-spatial-data-analysis.html#cb97-5" aria-hidden="true"></a><span class="cf">for</span> (column <span class="cf">in</span> <span class="kw">seq</span>(<span class="dv">2</span>,<span class="kw">ncol</span>(df),<span class="dv">24</span>)) {</span>
<span id="cb97-6"><a href="exploratory-spatial-data-analysis.html#cb97-6" aria-hidden="true"></a>    </span>
<span id="cb97-7"><a href="exploratory-spatial-data-analysis.html#cb97-7" aria-hidden="true"></a>  <span class="co"># index number of start column of age group</span></span>
<span id="cb97-8"><a href="exploratory-spatial-data-analysis.html#cb97-8" aria-hidden="true"></a>  start &lt;-<span class="st"> </span>column</span>
<span id="cb97-9"><a href="exploratory-spatial-data-analysis.html#cb97-9" aria-hidden="true"></a>  </span>
<span id="cb97-10"><a href="exploratory-spatial-data-analysis.html#cb97-10" aria-hidden="true"></a>  <span class="co"># index number of end column of age group</span></span>
<span id="cb97-11"><a href="exploratory-spatial-data-analysis.html#cb97-11" aria-hidden="true"></a>  stop &lt;-<span class="st"> </span>column <span class="op">+</span><span class="st"> </span><span class="dv">23</span> </span>
<span id="cb97-12"><a href="exploratory-spatial-data-analysis.html#cb97-12" aria-hidden="true"></a>  </span>
<span id="cb97-13"><a href="exploratory-spatial-data-analysis.html#cb97-13" aria-hidden="true"></a>  <span class="co"># call our function and assign it to the list</span></span>
<span id="cb97-14"><a href="exploratory-spatial-data-analysis.html#cb97-14" aria-hidden="true"></a>  df_lst[[<span class="kw">length</span>(df_lst)<span class="op">+</span><span class="dv">1</span>]] &lt;-<span class="st"> </span><span class="kw">columns_to_rows</span>(df,<span class="dt">start=</span>start,<span class="dt">stop=</span>stop)</span>
<span id="cb97-15"><a href="exploratory-spatial-data-analysis.html#cb97-15" aria-hidden="true"></a>}</span>
<span id="cb97-16"><a href="exploratory-spatial-data-analysis.html#cb97-16" aria-hidden="true"></a></span>
<span id="cb97-17"><a href="exploratory-spatial-data-analysis.html#cb97-17" aria-hidden="true"></a><span class="co"># paste all elements from the list underneath one another</span></span>
<span id="cb97-18"><a href="exploratory-spatial-data-analysis.html#cb97-18" aria-hidden="true"></a><span class="co"># do.call executes the function &#39;rbind&#39; for all elements in our list</span></span>
<span id="cb97-19"><a href="exploratory-spatial-data-analysis.html#cb97-19" aria-hidden="true"></a>df_reformatted &lt;-<span class="st"> </span><span class="kw">as_tibble</span>(<span class="kw">do.call</span>(rbind,df_lst))</span>
<span id="cb97-20"><a href="exploratory-spatial-data-analysis.html#cb97-20" aria-hidden="true"></a></span>
<span id="cb97-21"><a href="exploratory-spatial-data-analysis.html#cb97-21" aria-hidden="true"></a><span class="co"># and the result</span></span>
<span id="cb97-22"><a href="exploratory-spatial-data-analysis.html#cb97-22" aria-hidden="true"></a>df_reformatted</span></code></pre></div>
<pre><code>## # A tibble: 2,765,184 x 3
##    msoa11cd  age_group                                                     count
##    &lt;chr&gt;     &lt;chr&gt;                                                         &lt;dbl&gt;
##  1 E02002559 Sex: All persons; Age: Age 16 to 17; Ethnic Group: All categ…   215
##  2 E02002559 Sex: All persons; Age: Age 16 to 17; Ethnic Group: White: To…   206
##  3 E02002559 Sex: All persons; Age: Age 16 to 17; Ethnic Group: White: En…   204
##  4 E02002559 Sex: All persons; Age: Age 16 to 17; Ethnic Group: White: Ir…     0
##  5 E02002559 Sex: All persons; Age: Age 16 to 17; Ethnic Group: White: Gy…     2
##  6 E02002559 Sex: All persons; Age: Age 16 to 17; Ethnic Group: White: Ot…     0
##  7 E02002559 Sex: All persons; Age: Age 16 to 17; Ethnic Group: Mixed/mul…     4
##  8 E02002559 Sex: All persons; Age: Age 16 to 17; Ethnic Group: Mixed/mul…     1
##  9 E02002559 Sex: All persons; Age: Age 16 to 17; Ethnic Group: Mixed/mul…     2
## 10 E02002559 Sex: All persons; Age: Age 16 to 17; Ethnic Group: Mixed/mul…     1
## # … with 2,765,174 more rows</code></pre>
<p>Now the data is in a much more manageable format, we can move on with preparing the data further. We will start by filtering out the columns (now rows!) that contain <em>all categories</em> and the <em>within group totals</em>. We will do this by cleverly filtering our data set on only a part of the text string that is contained in the <em>age_group</em> column of our dataframe using a <a href="https://en.wikipedia.org/wiki/Regular_expression">regular expression</a>. We further truncate the information that is contained in the <em>age_group</em> column to make all a little more readable.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="exploratory-spatial-data-analysis.html#cb99-1" aria-hidden="true"></a><span class="co"># filter rows</span></span>
<span id="cb99-2"><a href="exploratory-spatial-data-analysis.html#cb99-2" aria-hidden="true"></a><span class="co"># this can be a little slow because of the regular expression!</span></span>
<span id="cb99-3"><a href="exploratory-spatial-data-analysis.html#cb99-3" aria-hidden="true"></a>df_reformatted &lt;-<span class="st"> </span><span class="kw">filter</span>(df_reformatted,<span class="op">!</span><span class="kw">grepl</span>(<span class="st">&#39;*All categories*&#39;</span>,age_group))</span>
<span id="cb99-4"><a href="exploratory-spatial-data-analysis.html#cb99-4" aria-hidden="true"></a>df_reformatted &lt;-<span class="st"> </span><span class="kw">filter</span>(df_reformatted,<span class="op">!</span><span class="kw">grepl</span>(<span class="st">&#39;*Total*&#39;</span>,age_group))</span>
<span id="cb99-5"><a href="exploratory-spatial-data-analysis.html#cb99-5" aria-hidden="true"></a></span>
<span id="cb99-6"><a href="exploratory-spatial-data-analysis.html#cb99-6" aria-hidden="true"></a><span class="co"># create variable that flags the 85 and over category</span></span>
<span id="cb99-7"><a href="exploratory-spatial-data-analysis.html#cb99-7" aria-hidden="true"></a><span class="co"># this can be a little slow because of the regular expression!</span></span>
<span id="cb99-8"><a href="exploratory-spatial-data-analysis.html#cb99-8" aria-hidden="true"></a>df_reformatted<span class="op">$</span>g &lt;-<span class="st"> </span><span class="kw">ifelse</span>(<span class="kw">grepl</span>(<span class="st">&#39;85&#39;</span>,<span class="kw">as.character</span>(df_reformatted<span class="op">$</span>age_group)),<span class="dv">1</span>,<span class="dv">0</span>)</span>
<span id="cb99-9"><a href="exploratory-spatial-data-analysis.html#cb99-9" aria-hidden="true"></a></span>
<span id="cb99-10"><a href="exploratory-spatial-data-analysis.html#cb99-10" aria-hidden="true"></a><span class="co"># select information from character 41 (85 and over category) or from character 38</span></span>
<span id="cb99-11"><a href="exploratory-spatial-data-analysis.html#cb99-11" aria-hidden="true"></a>df_reformatted &lt;-<span class="st"> </span><span class="kw">mutate</span>(df_reformatted,<span class="dt">group =</span> <span class="kw">ifelse</span>(g<span class="op">==</span><span class="dv">0</span>,<span class="kw">substr</span>(<span class="kw">as.character</span>(age_group),<span class="dv">38</span>,<span class="dv">500</span>),</span>
<span id="cb99-12"><a href="exploratory-spatial-data-analysis.html#cb99-12" aria-hidden="true"></a>                                                            <span class="kw">substr</span>(<span class="kw">as.character</span>(age_group),<span class="dv">41</span>,<span class="dv">500</span>))) </span>
<span id="cb99-13"><a href="exploratory-spatial-data-analysis.html#cb99-13" aria-hidden="true"></a></span>
<span id="cb99-14"><a href="exploratory-spatial-data-analysis.html#cb99-14" aria-hidden="true"></a><span class="co"># remove unnecessary columns</span></span>
<span id="cb99-15"><a href="exploratory-spatial-data-analysis.html#cb99-15" aria-hidden="true"></a>df_reformatted &lt;-<span class="st"> </span><span class="kw">select</span>(df_reformatted, <span class="op">-</span>age_group, <span class="op">-</span>g)</span></code></pre></div>
<p>We are now really getting somewhere, although in order for our data to be tidy each variable must have its own column. We also want, within each ethnic group, to aggregate the individual values within each age group.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="exploratory-spatial-data-analysis.html#cb100-1" aria-hidden="true"></a><span class="co"># pivot table and aggregate values</span></span>
<span id="cb100-2"><a href="exploratory-spatial-data-analysis.html#cb100-2" aria-hidden="true"></a>df_clean &lt;-<span class="st"> </span><span class="kw">pivot_wider</span>(df_reformatted,<span class="dt">names_from=</span>group,<span class="dt">values_from=</span>count,<span class="dt">values_fn=</span>sum)</span>
<span id="cb100-3"><a href="exploratory-spatial-data-analysis.html#cb100-3" aria-hidden="true"></a></span>
<span id="cb100-4"><a href="exploratory-spatial-data-analysis.html#cb100-4" aria-hidden="true"></a><span class="co"># rename columns</span></span>
<span id="cb100-5"><a href="exploratory-spatial-data-analysis.html#cb100-5" aria-hidden="true"></a><span class="co"># names are assigned based on index values, so make sure that the current columnnames match the</span></span>
<span id="cb100-6"><a href="exploratory-spatial-data-analysis.html#cb100-6" aria-hidden="true"></a><span class="co"># order of the new columnames otherwise our whole analysis will be wrong!</span></span>
<span id="cb100-7"><a href="exploratory-spatial-data-analysis.html#cb100-7" aria-hidden="true"></a><span class="kw">names</span>(df_clean) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;msoa11cd&#39;</span>,<span class="st">&#39;white_british&#39;</span>,<span class="st">&#39;white_irish&#39;</span>,<span class="st">&#39;white_traveller&#39;</span>,<span class="st">&#39;white_other&#39;</span>,<span class="st">&#39;mixed_white_black_caribbean&#39;</span>,</span>
<span id="cb100-8"><a href="exploratory-spatial-data-analysis.html#cb100-8" aria-hidden="true"></a>                     <span class="st">&#39;mixed_white_black_african&#39;</span>,<span class="st">&#39;mixed_white_asian&#39;</span>,<span class="st">&#39;mixed_other&#39;</span>,<span class="st">&#39;asian_indian&#39;</span>,<span class="st">&#39;asian_pakistani&#39;</span>,</span>
<span id="cb100-9"><a href="exploratory-spatial-data-analysis.html#cb100-9" aria-hidden="true"></a>                     <span class="st">&#39;asian_bangladeshi&#39;</span>,<span class="st">&#39;asian_chinese&#39;</span>,<span class="st">&#39;asian_other&#39;</span>,<span class="st">&#39;black_african&#39;</span>,<span class="st">&#39;black_caribbean&#39;</span>,<span class="st">&#39;black_other&#39;</span>,</span>
<span id="cb100-10"><a href="exploratory-spatial-data-analysis.html#cb100-10" aria-hidden="true"></a>                     <span class="st">&#39;other_arab&#39;</span>,<span class="st">&#39;other_other&#39;</span>)</span>
<span id="cb100-11"><a href="exploratory-spatial-data-analysis.html#cb100-11" aria-hidden="true"></a></span>
<span id="cb100-12"><a href="exploratory-spatial-data-analysis.html#cb100-12" aria-hidden="true"></a><span class="co"># tidy data</span></span>
<span id="cb100-13"><a href="exploratory-spatial-data-analysis.html#cb100-13" aria-hidden="true"></a>df_clean</span></code></pre></div>
<pre><code>## # A tibble: 7,201 x 19
##    msoa11cd white_british white_irish white_traveller white_other
##    &lt;chr&gt;            &lt;dbl&gt;       &lt;dbl&gt;           &lt;dbl&gt;       &lt;dbl&gt;
##  1 E020025…          6775          17              27          51
##  2 E020025…          4688          11               8          31
##  3 E020025…          4609          20               3          55
##  4 E020025…          4653           4               6         131
##  5 E020025…          4369          13               2          38
##  6 E020025…          7320          11               3          73
##  7 E020025…          4274          16               2          96
##  8 E020025…          4713          33              24         308
##  9 E020025…          5344          17              42         111
## 10 E020025…          4583          29               6         100
## # … with 7,191 more rows, and 14 more variables:
## #   mixed_white_black_caribbean &lt;dbl&gt;, mixed_white_black_african &lt;dbl&gt;,
## #   mixed_white_asian &lt;dbl&gt;, mixed_other &lt;dbl&gt;, asian_indian &lt;dbl&gt;,
## #   asian_pakistani &lt;dbl&gt;, asian_bangladeshi &lt;dbl&gt;, asian_chinese &lt;dbl&gt;,
## #   asian_other &lt;dbl&gt;, black_african &lt;dbl&gt;, black_caribbean &lt;dbl&gt;,
## #   black_other &lt;dbl&gt;, other_arab &lt;dbl&gt;, other_other &lt;dbl&gt;</code></pre>
<p>Finally. We now have a <strong>tidy dataset</strong> that we can work with!</p>
</div>
</div>
<div id="assignment_w05" class="section level3" number="5.2.4">
<h3><span class="header-section-number">5.2.4</span> Assignments</h3>
<div id="assignment-1" class="section level4 unnumbered">
<h4>Assignment 1</h4>
<p>Since we went through all the trouble of cleaning and creating this file, the first task for Friday’s seminar is to finalise the analysis: use the cleaned data set to create a table that, for each MSOA, contains the proportions of the population belonging to each of the ethnic groups in the UK 2011 Census of Population. It could look something like this:</p>
<table>
<thead>
<tr class="header">
<th align="left">msoa11cd</th>
<th align="center">white_british</th>
<th align="center">white_irish</th>
<th align="center">etc.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">E02002562</td>
<td align="center">0.74</td>
<td align="center">0.03</td>
<td align="center">…</td>
</tr>
<tr class="even">
<td align="left">E02002560</td>
<td align="center">0.32</td>
<td align="center">0.32</td>
<td align="center">…</td>
</tr>
</tbody>
</table>
</div>
<div id="tips" class="section level4 unnumbered">
<h4>Tips</h4>
<ol style="list-style-type: decimal">
<li>First think what you what steps you would need to take in order to get the group proportions. Write them down on a piece of paper if you like. Once you have identified the steps, then start coding.</li>
<li>Conduct sanity checks. Every time you have written a line of code, check the results to see if the code did indeed give the result that you expected to get.</li>
<li>Google is your friend. Do not be afraid to search for specific solutions and suggestions, chances are that there have been other people who have faces similar problems and posted their questions on <a href="https://stackoverflow.com/">stackoverflow</a>.</li>
</ol>
</div>
<div id="assignment-2" class="section level4 unnumbered">
<h4>Assignment 2</h4>
<p>Further to calculating the proportions of the population belonging to each of the ethnic groups in the UK 2011 Census of Population, we also want to make a choropleth map at district level of the UK population that is older than 60 as a proportion of the total population. For this analysis we have available one dataset with the administrative boundaries of the UK 2020 Local Authorithy Districts administrative geography and we have a <code>csv</code> file that holds population estimates for the UK in 2019. Use everything you have learned over the past weeks to produces this map. Some tips:</p>
</div>
<div id="tips-1" class="section level4 unnumbered">
<h4>Tips</h4>
<ol style="list-style-type: decimal">
<li>Inspect both the shapefile and the <code>csv</code> file to get an idea of how your data look like. Use any tool you like to do this inspection (ArcGIS, R, QGIS, Microsoft Excel, etc.).</li>
<li>The <code>csv</code> file does contain a mix of administrative geographies, and you will need to do some data cleaning by filtering out <em>Country</em>, <em>County</em>, <em>Metropolitan County</em>, and <em>Region</em> before you link the data to the shapefile.</li>
<li>You are in charge of deciding what software you want to use to visualise the data (ArcGIS, R, QGIS, etc.).</li>
<li>You now have to make your own decisions on how to go about this problem. Although this practical has so far covered some of the functions and strategies you might need, the data cleaning and data preparation process is not the same.</li>
</ol>
</div>
<div id="submit_w05" class="section level4" number="5.2.4.1">
<h4><span class="header-section-number">5.2.4.1</span> Map submission</h4>
<p>E-mail your final map as a <code>PDF</code> or <code>JPG</code> to <nobr><strong>j.t.vandijk [at] ucl.ac.uk</strong></nobr> before Friday morning <strong>09h00</strong> UK time (GMT+0). Also, ‘bring’ your final map with you to Friday’s seminar.</p>
</div>
<div id="file-download-1" class="section level4 unnumbered">
<h4>File download</h4>
<table>
<thead>
<tr class="header">
<th align="left">File</th>
<th align="left">Type</th>
<th align="left">Link</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Local Authorithy District boundaries 2020</td>
<td align="left"><code>shp</code></td>
<td align="left"><a href="https://github.com/jtvandijk/GEOG0114/tree/master/raw/zip/LADs_uk_2020.zip">Download</a></td>
</tr>
<tr class="even">
<td align="left">Mid-Year Population Estimates 2019</td>
<td align="left"><code>csv</code></td>
<td align="left"><a href="https://github.com/jtvandijk/GEOG0114/tree/master/raw/zip/mye_pop_2019.zip">Download</a></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="exploratory-spatial-data-analysis-in-r" class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> Exploratory spatial data analysis in R</h2>
<p>Exploratory Data Analysis got introduced in the the late 1970s by the American mathematician <a href="https://en.wikipedia.org/wiki/John_Tukey">John Tukey</a>. Tukey thought that in much data analysis there was much emphasis on statistical hypothesis testing and very little development of new hypotheses. He therefore made a distinction between <strong>confirmatory data analysis</strong> and <strong>exploratory data analysis (EDA)</strong>. EDA is a collection of descriptive techniques used to detect patterns, identify outliers, and form hypotheses from the data. An EDA typically involves descriptive statistics and data visualisation. Exploratory techniques generally stay ‘close’ to the original data. <strong>Exploratory spatial data analysis (ESDA)</strong> is the extension of exploratory data analysis (EDA) to the spatial realm.</p>
<div id="video-exploratory-spatial-data-analysis" class="section level3" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Video: Exploratory spatial data analysis</h3>
<p><div class="vembedr" align="left">
<div>
<iframe src="https://web.microsoftstream.com/embed/video/1a534d23-24e2-4f4a-aa38-f85a029ba19b?autoplay=false&amp;showinfo=true" width="533" height="300" style="border:none;"></iframe>
</div>
</div>
<a href="https://github.com/jtvandijk/GEOG0114/tree/master/slides/w05/w05_02_esda.pdf">[Lecture slides]</a> <a href="https://web.microsoftstream.com/video/1a534d23-24e2-4f4a-aa38-f85a029ba19b?list=studio">[Watch on MS stream]</a></p>
</div>
<div id="example-exploring-our-dataset" class="section level3" number="5.3.2">
<h3><span class="header-section-number">5.3.2</span> Example: Exploring our dataset</h3>
<p>After successfully creating the maps that we were requested to make, our bosses got so happy that they directly gave us a new assignment. This time they want us to look at bicycle theft in London, specifically they want to know which factors contribute to bicycle theft in London’s central boroughs of Southwark, Lambeth, Camden, Westminster, Tower Hamlets, City of London, and Hackney. For this assignment, we have access to two <strong>open</strong> datasets. The first one contains the English <a href="https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019">Index of Multiple Deprivation (IMD)</a> for 2019. The English indices of deprivation measure relative deprivation in small areas in England called Lower-layer Super Output Areas (LSOAs) The index of multiple deprivation is the most widely used of these indices. The second dataset contains some of the input data that have been used to create the <a href="https://data.cdrc.ac.uk/dataset/access-healthy-assets-hazards-ahah">Access to Healthy Assets and Hazards (AHAH)</a>. AHAH is a multi-dimensional index developed by the <a href="https://www.cdrc.ac.uk/">Consumer Data Research Centre (CDRC)</a> for Great Britain measuring how ‘healthy’ neighbourhoods are. We also have access to the LSOAs for London. Further to these two open datasets, we have a shapefile with all of London’s LSOAs as well as a <code>csv</code> file that contains the coordinates of all tube stations.</p>
<div id="file-download-2" class="section level4 unnumbered">
<h4>File download</h4>
<table>
<thead>
<tr class="header">
<th align="left">File</th>
<th align="left">Type</th>
<th align="left">Link</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Lower-layer Super Output Areas London 2011</td>
<td align="left"><code>shp</code></td>
<td align="left"><a href="https://github.com/jtvandijk/GEOG0114/tree/master/raw/zip/lsoa_london_2011_sel.zip">Download</a></td>
</tr>
<tr class="even">
<td align="left">Bicycle theft data London 2019</td>
<td align="left"><code>csv</code></td>
<td align="left"><a href="https://github.com/jtvandijk/GEOG0114/tree/master/raw/zip/2019_london_bicycle_theft.zip">Download</a></td>
</tr>
<tr class="odd">
<td align="left">Index of Multiple Deprivation London 2019</td>
<td align="left"><code>csv</code></td>
<td align="left"><a href="https://github.com/jtvandijk/GEOG0114/tree/master/raw/zip/imd_ew_2019.zip">Download</a></td>
</tr>
<tr class="even">
<td align="left">Access to Healthy Assets and Hazards (AHAH) London</td>
<td align="left"><code>csv</code></td>
<td align="left"><a href="https://github.com/jtvandijk/GEOG0114/tree/master/raw/zip/ahah_input_gb_2016.zip">Download</a></td>
</tr>
<tr class="odd">
<td align="left">Locations of tube stations in London</td>
<td align="left"><code>csv</code></td>
<td align="left"><a href="https://github.com/jtvandijk/GEOG0114/tree/master/raw/zip/london_underground_stations.zip">Download</a></td>
</tr>
</tbody>
</table>
<p>Download the individual files to your own computer and again make sure <a href="spatial-autocorrelation.html#setting-up-the-environment">your data directory</a> is set up correctly and the data are unzipped. Then load the libraries and the data into R.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="exploratory-spatial-data-analysis.html#cb102-1" aria-hidden="true"></a><span class="co"># load libraries</span></span>
<span id="cb102-2"><a href="exploratory-spatial-data-analysis.html#cb102-2" aria-hidden="true"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb102-3"><a href="exploratory-spatial-data-analysis.html#cb102-3" aria-hidden="true"></a><span class="kw">library</span>(sf)</span>
<span id="cb102-4"><a href="exploratory-spatial-data-analysis.html#cb102-4" aria-hidden="true"></a><span class="kw">library</span>(tmap)</span>
<span id="cb102-5"><a href="exploratory-spatial-data-analysis.html#cb102-5" aria-hidden="true"></a><span class="kw">library</span>(Rfast)</span>
<span id="cb102-6"><a href="exploratory-spatial-data-analysis.html#cb102-6" aria-hidden="true"></a></span>
<span id="cb102-7"><a href="exploratory-spatial-data-analysis.html#cb102-7" aria-hidden="true"></a><span class="co"># load spatial data</span></span>
<span id="cb102-8"><a href="exploratory-spatial-data-analysis.html#cb102-8" aria-hidden="true"></a>lsoa &lt;-<span class="st"> </span><span class="kw">st_read</span>(<span class="st">&#39;raw/boundaries/london_lsoa_2011/lsoa_london_2011_sel.shp&#39;</span>)</span></code></pre></div>
<pre><code>## Reading layer `lsoa_london_2011_sel&#39; from data source `/Users/Tycho/Dropbox/UCL/Web/jtvandijk.github.io/GEOG0114/raw/boundaries/london_lsoa_2011/lsoa_london_2011_sel.shp&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 1020 features and 1 field
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: 523847.7 ymin: 169650 xmax: 539533.3 ymax: 188327.4
## CRS:            27700</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="exploratory-spatial-data-analysis.html#cb104-1" aria-hidden="true"></a><span class="kw">names</span>(lsoa) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;lsoa11cd&#39;</span>,<span class="st">&#39;geometry&#39;</span>)</span>
<span id="cb104-2"><a href="exploratory-spatial-data-analysis.html#cb104-2" aria-hidden="true"></a></span>
<span id="cb104-3"><a href="exploratory-spatial-data-analysis.html#cb104-3" aria-hidden="true"></a><span class="co"># load data</span></span>
<span id="cb104-4"><a href="exploratory-spatial-data-analysis.html#cb104-4" aria-hidden="true"></a>crime &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&#39;raw/crime/2019_london_bicycle_theft.csv&#39;</span>)</span>
<span id="cb104-5"><a href="exploratory-spatial-data-analysis.html#cb104-5" aria-hidden="true"></a>imd &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&#39;raw/index/imd_ew_2019.csv&#39;</span>)</span>
<span id="cb104-6"><a href="exploratory-spatial-data-analysis.html#cb104-6" aria-hidden="true"></a>ahah &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&#39;raw/index/ahah_input_gb_2016.csv&#39;</span>)</span>
<span id="cb104-7"><a href="exploratory-spatial-data-analysis.html#cb104-7" aria-hidden="true"></a>tube &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&#39;raw/locations/london_underground_stations.csv&#39;</span>)</span>
<span id="cb104-8"><a href="exploratory-spatial-data-analysis.html#cb104-8" aria-hidden="true"></a></span>
<span id="cb104-9"><a href="exploratory-spatial-data-analysis.html#cb104-9" aria-hidden="true"></a><span class="co"># inspect crime data</span></span>
<span id="cb104-10"><a href="exploratory-spatial-data-analysis.html#cb104-10" aria-hidden="true"></a><span class="kw">head</span>(crime)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   month      long   lat type         
##   &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;        
## 1 2019-03 -0.0981  51.5 Bicycle theft
## 2 2019-03 -0.0981  51.5 Bicycle theft
## 3 2019-03 -0.0976  51.5 Bicycle theft
## 4 2019-03 -0.0930  51.5 Bicycle theft
## 5 2019-03 -0.0941  51.5 Bicycle theft
## 6 2019-03 -0.0930  51.5 Bicycle theft</code></pre>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="exploratory-spatial-data-analysis.html#cb106-1" aria-hidden="true"></a><span class="co"># inspect imd data</span></span>
<span id="cb106-2"><a href="exploratory-spatial-data-analysis.html#cb106-2" aria-hidden="true"></a><span class="kw">head</span>(imd)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   lsoa11cd  imd_rank imd_dec
##   &lt;chr&gt;     &lt;chr&gt;      &lt;dbl&gt;
## 1 E01000001 29 199         9
## 2 E01000002 30 379        10
## 3 E01000003 14 915         5
## 4 E01000005 8 678          3
## 5 E01000006 14 486         5
## 6 E01000007 7 256          3</code></pre>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="exploratory-spatial-data-analysis.html#cb108-1" aria-hidden="true"></a><span class="co"># inspect ahah data</span></span>
<span id="cb108-2"><a href="exploratory-spatial-data-analysis.html#cb108-2" aria-hidden="true"></a><span class="kw">head</span>(ahah)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   lsoa11cd  gamb_dist pubs_dist off_dist
##   &lt;chr&gt;         &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 E01000001     0.390     0.181    0.381
## 2 E01000002     0.417     0.221    0.680
## 3 E01000003     0.398     0.192    0.422
## 4 E01000005     0.280     0.228    0.617
## 5 E01000006     0.599     0.611    0.648
## 6 E01000007     0.377     0.621    0.734</code></pre>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="exploratory-spatial-data-analysis.html#cb110-1" aria-hidden="true"></a><span class="co"># inspect tube location data</span></span>
<span id="cb110-2"><a href="exploratory-spatial-data-analysis.html#cb110-2" aria-hidden="true"></a><span class="kw">head</span>(tube)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   station             lat     long
##   &lt;chr&gt;             &lt;dbl&gt;    &lt;dbl&gt;
## 1 Abbey Road         51.5  0.00372
## 2 Abbey Wood         51.5  0.120  
## 3 Acton Central      51.5 -0.263  
## 4 Acton Main Line    51.5 -0.268  
## 5 Acton Town         51.5 -0.280  
## 6 Addington Village  51.4 -0.0327</code></pre>
<p>Looking at the data you will notice that both the bike theft data and the tube location data exist of longitudes and latitudes. The IMD dataset has an <em>lsoa11cd</em> column, an IMD rank column, and an IMD decile column. The AHAH dataset has an <em>lsoa11cd</em> column, a distance to the nearest gamling outlet column, a distance to the nearest pub column, and a distance to the nearest off license column. The <a href="https://figshare.com/articles/Access_to_Healthy_Assets_and_Hazards_AHAH_-_Updated_version_2017/8295842/1">technical report of the AHAH index</a> suggests these distances represent the mean distance (kilometres) by car of all postcodes within each LSOA to the nearest outlet. Good to know!</p>
<p>Let’s start by linking the IMD dataset and the AHAH dataset to the spatial dataset. Since we are using <code>sf</code> for our spatial data, we can very easily join them together using the common variable in these datasets: <em>lsoa11cd</em>.</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="exploratory-spatial-data-analysis.html#cb112-1" aria-hidden="true"></a><span class="co"># join imd data</span></span>
<span id="cb112-2"><a href="exploratory-spatial-data-analysis.html#cb112-2" aria-hidden="true"></a>lsoa_join &lt;-<span class="st"> </span><span class="kw">left_join</span>(lsoa,imd,<span class="dt">by=</span><span class="kw">c</span>(<span class="st">&#39;lsoa11cd&#39;</span>))</span>
<span id="cb112-3"><a href="exploratory-spatial-data-analysis.html#cb112-3" aria-hidden="true"></a></span>
<span id="cb112-4"><a href="exploratory-spatial-data-analysis.html#cb112-4" aria-hidden="true"></a><span class="co"># join ahah data</span></span>
<span id="cb112-5"><a href="exploratory-spatial-data-analysis.html#cb112-5" aria-hidden="true"></a>lsoa_join &lt;-<span class="st"> </span><span class="kw">left_join</span>(lsoa_join,ahah,<span class="dt">by=</span><span class="kw">c</span>(<span class="st">&#39;lsoa11cd&#39;</span>))</span>
<span id="cb112-6"><a href="exploratory-spatial-data-analysis.html#cb112-6" aria-hidden="true"></a></span>
<span id="cb112-7"><a href="exploratory-spatial-data-analysis.html#cb112-7" aria-hidden="true"></a><span class="co"># inspect the result</span></span>
<span id="cb112-8"><a href="exploratory-spatial-data-analysis.html#cb112-8" aria-hidden="true"></a><span class="kw">head</span>(lsoa_join)</span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 6 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: 525360.9 ymin: 177857 xmax: 538921.5 ymax: 183191.6
## CRS:            27700
##    lsoa11cd imd_rank imd_dec gamb_dist pubs_dist  off_dist
## 1 E01004665    5 376       2 0.2504762 0.2019048 0.4619048
## 2 E01003111    5 781       2 0.4455556 0.2648148 0.4603704
## 3 E01004276   30 144      10 0.8789286 0.1492857 1.8007143
## 4 E01004706   27 823       9 0.6737500 0.7354167 0.3750000
##                         geometry
## 1 MULTIPOLYGON (((529040.9 17...
## 2 MULTIPOLYGON (((531023.1 17...
## 3 MULTIPOLYGON (((537563.7 17...
## 4 MULTIPOLYGON (((525406.7 18...
##  [ reached &#39;max&#39; / getOption(&quot;max.print&quot;) -- omitted 2 rows ]</code></pre>
<p>This is all looking fine. Let’s now turn our turn our bike theft location dataset into a spatial dataset using the longitude and latitude values and get total bike theft counts within each of our available LSOAs.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="exploratory-spatial-data-analysis.html#cb114-1" aria-hidden="true"></a><span class="co"># filter out points without a longitude and/or latitude value</span></span>
<span id="cb114-2"><a href="exploratory-spatial-data-analysis.html#cb114-2" aria-hidden="true"></a>crime &lt;-<span class="st"> </span><span class="kw">filter</span>(crime,<span class="op">!</span><span class="kw">is.na</span>(long) <span class="op">|</span><span class="st"> </span><span class="op">!</span><span class="kw">is.na</span>(lat))</span>
<span id="cb114-3"><a href="exploratory-spatial-data-analysis.html#cb114-3" aria-hidden="true"></a>crime_points &lt;-<span class="st"> </span><span class="kw">st_as_sf</span>(crime, <span class="dt">coords=</span><span class="kw">c</span>(<span class="st">&#39;long&#39;</span>,<span class="st">&#39;lat&#39;</span>),<span class="dt">crs=</span><span class="dv">4326</span>)</span>
<span id="cb114-4"><a href="exploratory-spatial-data-analysis.html#cb114-4" aria-hidden="true"></a></span>
<span id="cb114-5"><a href="exploratory-spatial-data-analysis.html#cb114-5" aria-hidden="true"></a><span class="co"># project into british national grid (epsg 27700)</span></span>
<span id="cb114-6"><a href="exploratory-spatial-data-analysis.html#cb114-6" aria-hidden="true"></a>crime_points &lt;-<span class="st"> </span><span class="kw">st_transform</span>(crime_points,<span class="dv">27700</span>)</span>
<span id="cb114-7"><a href="exploratory-spatial-data-analysis.html#cb114-7" aria-hidden="true"></a></span>
<span id="cb114-8"><a href="exploratory-spatial-data-analysis.html#cb114-8" aria-hidden="true"></a><span class="co"># count the number of points intersecting within each of London&#39;s LSOAs</span></span>
<span id="cb114-9"><a href="exploratory-spatial-data-analysis.html#cb114-9" aria-hidden="true"></a>lsoa_join<span class="op">$</span>n_crime &lt;-<span class="st"> </span><span class="kw">lengths</span>(<span class="kw">st_intersects</span>(lsoa_join,crime_points))</span>
<span id="cb114-10"><a href="exploratory-spatial-data-analysis.html#cb114-10" aria-hidden="true"></a></span>
<span id="cb114-11"><a href="exploratory-spatial-data-analysis.html#cb114-11" aria-hidden="true"></a><span class="co"># inspect the result</span></span>
<span id="cb114-12"><a href="exploratory-spatial-data-analysis.html#cb114-12" aria-hidden="true"></a><span class="kw">tm_shape</span>(lsoa_join) <span class="op">+</span></span>
<span id="cb114-13"><a href="exploratory-spatial-data-analysis.html#cb114-13" aria-hidden="true"></a><span class="st">  </span><span class="kw">tm_fill</span>(<span class="dt">col=</span><span class="st">&#39;n_crime&#39;</span>)</span></code></pre></div>
<p><img src="GEOG0114_files/figure-html/05-points-to-lsoa-1.png" width="672" /></p>
<p>This all looks good. We can see, however, that the the number of times bike theft was reported are highly skewed by Central London. It is now a good idea to explore the bike theft data a bit further to see how the data are distributed non-spatially by plotting them.</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="exploratory-spatial-data-analysis.html#cb115-1" aria-hidden="true"></a><span class="co"># summary</span></span>
<span id="cb115-2"><a href="exploratory-spatial-data-analysis.html#cb115-2" aria-hidden="true"></a><span class="kw">summary</span>(lsoa_join<span class="op">$</span>n_crime)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   2.000   4.000   8.993  10.000 260.000</code></pre>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="exploratory-spatial-data-analysis.html#cb117-1" aria-hidden="true"></a><span class="co"># histogram</span></span>
<span id="cb117-2"><a href="exploratory-spatial-data-analysis.html#cb117-2" aria-hidden="true"></a><span class="kw">ggplot</span>(lsoa_join, <span class="kw">aes</span>(<span class="dt">x=</span>n_crime)) <span class="op">+</span></span>
<span id="cb117-3"><a href="exploratory-spatial-data-analysis.html#cb117-3" aria-hidden="true"></a><span class="st">    </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth=</span>.<span class="dv">5</span>, <span class="dt">colour=</span><span class="st">&#39;black&#39;</span>, <span class="dt">fill=</span><span class="st">&#39;white&#39;</span>)</span></code></pre></div>
<p><img src="GEOG0114_files/figure-html/05-inspect-the-crime-data-1.png" width="672" /></p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="exploratory-spatial-data-analysis.html#cb118-1" aria-hidden="true"></a><span class="co"># boxplot</span></span>
<span id="cb118-2"><a href="exploratory-spatial-data-analysis.html#cb118-2" aria-hidden="true"></a><span class="kw">ggplot</span>(lsoa_join, <span class="kw">aes</span>(<span class="dt">x=</span>n_crime))<span class="op">+</span></span>
<span id="cb118-3"><a href="exploratory-spatial-data-analysis.html#cb118-3" aria-hidden="true"></a><span class="st"> </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="GEOG0114_files/figure-html/05-inspect-the-crime-data-2.png" width="672" /></p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="exploratory-spatial-data-analysis.html#cb119-1" aria-hidden="true"></a><span class="co"># as the data is very skewed, let&#39;s cube transform the bike theft data </span></span>
<span id="cb119-2"><a href="exploratory-spatial-data-analysis.html#cb119-2" aria-hidden="true"></a><span class="co"># and inspect the transformed data again</span></span>
<span id="cb119-3"><a href="exploratory-spatial-data-analysis.html#cb119-3" aria-hidden="true"></a>lsoa_join<span class="op">$</span>n_crime_cube &lt;-<span class="st"> </span><span class="kw">abs</span>(lsoa_join<span class="op">$</span>n_crime)<span class="op">^</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">3</span>)</span>
<span id="cb119-4"><a href="exploratory-spatial-data-analysis.html#cb119-4" aria-hidden="true"></a></span>
<span id="cb119-5"><a href="exploratory-spatial-data-analysis.html#cb119-5" aria-hidden="true"></a><span class="co"># summary</span></span>
<span id="cb119-6"><a href="exploratory-spatial-data-analysis.html#cb119-6" aria-hidden="true"></a><span class="kw">summary</span>(lsoa_join<span class="op">$</span>n_crime_cube)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   1.260   1.587   1.666   2.154   6.383</code></pre>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="exploratory-spatial-data-analysis.html#cb121-1" aria-hidden="true"></a><span class="co"># histogram</span></span>
<span id="cb121-2"><a href="exploratory-spatial-data-analysis.html#cb121-2" aria-hidden="true"></a><span class="kw">ggplot</span>(lsoa_join, <span class="kw">aes</span>(<span class="dt">x=</span>n_crime_cube)) <span class="op">+</span></span>
<span id="cb121-3"><a href="exploratory-spatial-data-analysis.html#cb121-3" aria-hidden="true"></a><span class="st">    </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth=</span>.<span class="dv">5</span>, <span class="dt">colour=</span><span class="st">&#39;black&#39;</span>, <span class="dt">fill=</span><span class="st">&#39;white&#39;</span>)</span></code></pre></div>
<p><img src="GEOG0114_files/figure-html/05-inspect-the-crime-data-3.png" width="672" /></p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="exploratory-spatial-data-analysis.html#cb122-1" aria-hidden="true"></a><span class="co"># boxplot</span></span>
<span id="cb122-2"><a href="exploratory-spatial-data-analysis.html#cb122-2" aria-hidden="true"></a><span class="kw">ggplot</span>(lsoa_join, <span class="kw">aes</span>(<span class="dt">x=</span>n_crime_cube))<span class="op">+</span></span>
<span id="cb122-3"><a href="exploratory-spatial-data-analysis.html#cb122-3" aria-hidden="true"></a><span class="st"> </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="GEOG0114_files/figure-html/05-inspect-the-crime-data-4.png" width="672" /></p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="exploratory-spatial-data-analysis.html#cb123-1" aria-hidden="true"></a><span class="co"># inspect the result</span></span>
<span id="cb123-2"><a href="exploratory-spatial-data-analysis.html#cb123-2" aria-hidden="true"></a><span class="kw">tm_shape</span>(lsoa_join) <span class="op">+</span></span>
<span id="cb123-3"><a href="exploratory-spatial-data-analysis.html#cb123-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">tm_fill</span>(<span class="dt">col=</span><span class="st">&#39;n_crime_cube&#39;</span>)</span></code></pre></div>
<p><img src="GEOG0114_files/figure-html/05-inspect-the-crime-data-5.png" width="672" /></p>
<p>This does look much better, although there are clearly several outliers in our data set with some areas that have a higher number of cases of bike theft. Let’s now also inspect our input data before we start to see whether there is a relationship between our independent variables and our dependent variable (i.e. the number of cases of bike theft).</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="exploratory-spatial-data-analysis.html#cb124-1" aria-hidden="true"></a><span class="co"># summary imd deciles</span></span>
<span id="cb124-2"><a href="exploratory-spatial-data-analysis.html#cb124-2" aria-hidden="true"></a><span class="kw">summary</span>(lsoa_join[,<span class="dv">4</span>])</span></code></pre></div>
<pre><code>##    gamb_dist               geometry   
##  Min.   :0.1230   MULTIPOLYGON :1020  
##  1st Qu.:0.3362   epsg:27700   :   0  
##  Median :0.4603   +proj=tmer...:   0  
##  Mean   :0.5189                       
##  3rd Qu.:0.6268                       
##  Max.   :3.8188</code></pre>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="exploratory-spatial-data-analysis.html#cb126-1" aria-hidden="true"></a><span class="co"># boxplot imd deciles</span></span>
<span id="cb126-2"><a href="exploratory-spatial-data-analysis.html#cb126-2" aria-hidden="true"></a><span class="kw">ggplot</span>(lsoa_join, <span class="kw">aes</span>(<span class="dt">x=</span>imd_dec))<span class="op">+</span></span>
<span id="cb126-3"><a href="exploratory-spatial-data-analysis.html#cb126-3" aria-hidden="true"></a><span class="st"> </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="GEOG0114_files/figure-html/05-inspect-the-input-data-1.png" width="672" /></p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="exploratory-spatial-data-analysis.html#cb127-1" aria-hidden="true"></a><span class="co"># summary ahah</span></span>
<span id="cb127-2"><a href="exploratory-spatial-data-analysis.html#cb127-2" aria-hidden="true"></a><span class="kw">summary</span>(lsoa_join[,<span class="dv">5</span><span class="op">:</span><span class="dv">7</span>])</span></code></pre></div>
<pre><code>##    pubs_dist          off_dist               geometry   
##  Min.   :0.06364   Min.   :0.1574   MULTIPOLYGON :1020  
##  1st Qu.:0.22088   1st Qu.:0.4110   epsg:27700   :   0  
##  Median :0.32001   Median :0.5723   +proj=tmer...:   0  
##  Mean   :0.37230   Mean   :0.6586                       
##  3rd Qu.:0.47544   3rd Qu.:0.8262                       
##  Max.   :1.59219   Max.   :2.0869</code></pre>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="exploratory-spatial-data-analysis.html#cb129-1" aria-hidden="true"></a><span class="co"># boplot ahah pub distance</span></span>
<span id="cb129-2"><a href="exploratory-spatial-data-analysis.html#cb129-2" aria-hidden="true"></a><span class="kw">ggplot</span>(lsoa_join, <span class="kw">aes</span>(<span class="dt">x=</span>gamb_dist))<span class="op">+</span></span>
<span id="cb129-3"><a href="exploratory-spatial-data-analysis.html#cb129-3" aria-hidden="true"></a><span class="st"> </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="GEOG0114_files/figure-html/05-inspect-the-input-data-2.png" width="672" /></p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="exploratory-spatial-data-analysis.html#cb130-1" aria-hidden="true"></a><span class="co"># boplot ahah off license distance</span></span>
<span id="cb130-2"><a href="exploratory-spatial-data-analysis.html#cb130-2" aria-hidden="true"></a><span class="kw">ggplot</span>(lsoa_join, <span class="kw">aes</span>(<span class="dt">x=</span>off_dist))<span class="op">+</span></span>
<span id="cb130-3"><a href="exploratory-spatial-data-analysis.html#cb130-3" aria-hidden="true"></a><span class="st"> </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="GEOG0114_files/figure-html/05-inspect-the-input-data-3.png" width="672" /></p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="exploratory-spatial-data-analysis.html#cb131-1" aria-hidden="true"></a><span class="co"># gambling distance vs bike theft </span></span>
<span id="cb131-2"><a href="exploratory-spatial-data-analysis.html#cb131-2" aria-hidden="true"></a><span class="kw">ggplot</span>(lsoa_join,<span class="kw">aes</span>(<span class="dt">x=</span>gamb_dist, <span class="dt">y=</span>n_crime_cube)) <span class="op">+</span></span>
<span id="cb131-3"><a href="exploratory-spatial-data-analysis.html#cb131-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>()</span></code></pre></div>
<p><img src="GEOG0114_files/figure-html/05-inspect-the-input-data-4.png" width="672" /></p>
<p>The input data look good. There are no real strange and unexpected outliers or missing values. At the same time there is enough <a href="https://en.wikipedia.org/wiki/Homogeneity_and_heterogeneity">heterogeneity</a> in our data. This is important because if the input data have very similar values for al LSOAs they would not be very useful in trying to explain the differences in bike theft. However, we have not touched our tube locations dataset just yet. Perhaps bicycle theft happens more around tube stations? Let’s do some quick spatial analysis and add for each LSOA the distance to the nearest tube station to our dataset.</p>
<blockquote>
<p>Please note: the following operation requires some computing power as for all of our selected LSOAs in London we are going to calculate the euclidean distance from its centroid to all tube stations and create a <strong>distance matrix</strong>. In case the calculation takes too much time on your computer, you can download the <a href="https://github.com/jtvandijk/GEOG0114/tree/master/raw/zip/dist_matrix.zip">distance matrix</a> instead and use <code>dist_matrix &lt;- data.matrix(read_csv('path_to_file'))</code> to continue with the practical.</p>
</blockquote>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="exploratory-spatial-data-analysis.html#cb132-1" aria-hidden="true"></a><span class="co"># create a point dataset from the tube csv file</span></span>
<span id="cb132-2"><a href="exploratory-spatial-data-analysis.html#cb132-2" aria-hidden="true"></a>tube_points &lt;-<span class="st"> </span><span class="kw">st_as_sf</span>(tube, <span class="dt">coords=</span><span class="kw">c</span>(<span class="st">&#39;long&#39;</span>,<span class="st">&#39;lat&#39;</span>),<span class="dt">crs=</span><span class="dv">4326</span>)</span>
<span id="cb132-3"><a href="exploratory-spatial-data-analysis.html#cb132-3" aria-hidden="true"></a></span>
<span id="cb132-4"><a href="exploratory-spatial-data-analysis.html#cb132-4" aria-hidden="true"></a><span class="co"># project into british national grid (epsg 27700)</span></span>
<span id="cb132-5"><a href="exploratory-spatial-data-analysis.html#cb132-5" aria-hidden="true"></a>tube_points &lt;-<span class="st"> </span><span class="kw">st_transform</span>(tube_points,<span class="dv">27700</span>)</span>
<span id="cb132-6"><a href="exploratory-spatial-data-analysis.html#cb132-6" aria-hidden="true"></a></span>
<span id="cb132-7"><a href="exploratory-spatial-data-analysis.html#cb132-7" aria-hidden="true"></a><span class="co"># create a distance matrix</span></span>
<span id="cb132-8"><a href="exploratory-spatial-data-analysis.html#cb132-8" aria-hidden="true"></a>dist_matrix &lt;-<span class="st"> </span><span class="kw">st_distance</span>(<span class="kw">st_centroid</span>(lsoa_join),tube_points)</span></code></pre></div>
<pre><code>## Warning in st_centroid.sf(lsoa_join): st_centroid assumes attributes are
## constant over geometries of x</code></pre>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="exploratory-spatial-data-analysis.html#cb134-1" aria-hidden="true"></a><span class="co"># assign the distance of the closes tube station </span></span>
<span id="cb134-2"><a href="exploratory-spatial-data-analysis.html#cb134-2" aria-hidden="true"></a>lsoa_join<span class="op">$</span>tube_dist &lt;-<span class="st"> </span><span class="kw">rowMins</span>(dist_matrix,<span class="dt">value=</span><span class="ot">TRUE</span>)</span></code></pre></div>
<p>Great. So, now we can continue. Let’s start by seeing if there is any visual relationship between our input (independent) variables and our output (dependent) variable by plotting them against each other.</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="exploratory-spatial-data-analysis.html#cb135-1" aria-hidden="true"></a><span class="co"># imd decile vs bike theft </span></span>
<span id="cb135-2"><a href="exploratory-spatial-data-analysis.html#cb135-2" aria-hidden="true"></a><span class="kw">ggplot</span>(lsoa_join,<span class="kw">aes</span>(<span class="dt">x=</span>imd_dec, <span class="dt">y=</span>n_crime_cube)) <span class="op">+</span></span>
<span id="cb135-3"><a href="exploratory-spatial-data-analysis.html#cb135-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>()</span></code></pre></div>
<p><img src="GEOG0114_files/figure-html/05-lets-scatterplot-1.png" width="672" /></p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="exploratory-spatial-data-analysis.html#cb136-1" aria-hidden="true"></a><span class="co"># pub distance vs bike theft </span></span>
<span id="cb136-2"><a href="exploratory-spatial-data-analysis.html#cb136-2" aria-hidden="true"></a><span class="kw">ggplot</span>(lsoa_join,<span class="kw">aes</span>(<span class="dt">x=</span>pubs_dist, <span class="dt">y=</span>n_crime_cube)) <span class="op">+</span></span>
<span id="cb136-3"><a href="exploratory-spatial-data-analysis.html#cb136-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>()</span></code></pre></div>
<p><img src="GEOG0114_files/figure-html/05-lets-scatterplot-2.png" width="672" /></p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="exploratory-spatial-data-analysis.html#cb137-1" aria-hidden="true"></a><span class="co"># gambling outlets distance vs bike theft </span></span>
<span id="cb137-2"><a href="exploratory-spatial-data-analysis.html#cb137-2" aria-hidden="true"></a><span class="kw">ggplot</span>(lsoa_join,<span class="kw">aes</span>(<span class="dt">x=</span>gamb_dist, <span class="dt">y=</span>n_crime_cube)) <span class="op">+</span></span>
<span id="cb137-3"><a href="exploratory-spatial-data-analysis.html#cb137-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>()</span></code></pre></div>
<p><img src="GEOG0114_files/figure-html/05-lets-scatterplot-3.png" width="672" /></p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="exploratory-spatial-data-analysis.html#cb138-1" aria-hidden="true"></a><span class="co"># off license distance vs bike theft </span></span>
<span id="cb138-2"><a href="exploratory-spatial-data-analysis.html#cb138-2" aria-hidden="true"></a><span class="kw">ggplot</span>(lsoa_join,<span class="kw">aes</span>(<span class="dt">x=</span>off_dist, <span class="dt">y=</span>n_crime_cube)) <span class="op">+</span></span>
<span id="cb138-3"><a href="exploratory-spatial-data-analysis.html#cb138-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>()</span></code></pre></div>
<p><img src="GEOG0114_files/figure-html/05-lets-scatterplot-4.png" width="672" /></p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="exploratory-spatial-data-analysis.html#cb139-1" aria-hidden="true"></a><span class="co"># tube station distance vs bike theft </span></span>
<span id="cb139-2"><a href="exploratory-spatial-data-analysis.html#cb139-2" aria-hidden="true"></a><span class="kw">ggplot</span>(lsoa_join,<span class="kw">aes</span>(<span class="dt">x=</span>tube_dist, <span class="dt">y=</span>n_crime_cube)) <span class="op">+</span></span>
<span id="cb139-3"><a href="exploratory-spatial-data-analysis.html#cb139-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>()</span></code></pre></div>
<p><img src="GEOG0114_files/figure-html/05-lets-scatterplot-5.png" width="672" /></p>
<p>The IMD deciles, which are in fact categorical data, do not show any obvious pattern, however, the distance to the various outlets do show some pattern. Let’s correlate.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="exploratory-spatial-data-analysis.html#cb140-1" aria-hidden="true"></a><span class="co"># imd decile vs bike theft</span></span>
<span id="cb140-2"><a href="exploratory-spatial-data-analysis.html#cb140-2" aria-hidden="true"></a><span class="kw">cor</span>(lsoa_join<span class="op">$</span>imd_dec,lsoa_join<span class="op">$</span>n_crime_cube)</span></code></pre></div>
<pre><code>## [1] 0.05715025</code></pre>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="exploratory-spatial-data-analysis.html#cb142-1" aria-hidden="true"></a><span class="co"># gambling outlet distance vs bike theft</span></span>
<span id="cb142-2"><a href="exploratory-spatial-data-analysis.html#cb142-2" aria-hidden="true"></a><span class="kw">cor</span>(lsoa_join<span class="op">$</span>gamb_dist,lsoa_join<span class="op">$</span>n_crime_cube)</span></code></pre></div>
<pre><code>## [1] -0.2768482</code></pre>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="exploratory-spatial-data-analysis.html#cb144-1" aria-hidden="true"></a><span class="co"># pub distance vs bike theft</span></span>
<span id="cb144-2"><a href="exploratory-spatial-data-analysis.html#cb144-2" aria-hidden="true"></a><span class="kw">cor</span>(lsoa_join<span class="op">$</span>pubs_dist,lsoa_join<span class="op">$</span>n_crime_cube)</span></code></pre></div>
<pre><code>## [1] -0.4175234</code></pre>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="exploratory-spatial-data-analysis.html#cb146-1" aria-hidden="true"></a><span class="co"># off license distance vs bike theft</span></span>
<span id="cb146-2"><a href="exploratory-spatial-data-analysis.html#cb146-2" aria-hidden="true"></a><span class="kw">cor</span>(lsoa_join<span class="op">$</span>off_dist,lsoa_join<span class="op">$</span>n_crime_cube)</span></code></pre></div>
<pre><code>## [1] -0.1750449</code></pre>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="exploratory-spatial-data-analysis.html#cb148-1" aria-hidden="true"></a><span class="co"># tube location distance vs bike theft</span></span>
<span id="cb148-2"><a href="exploratory-spatial-data-analysis.html#cb148-2" aria-hidden="true"></a><span class="kw">cor</span>(lsoa_join<span class="op">$</span>off_dist,lsoa_join<span class="op">$</span>n_crime_cube)</span></code></pre></div>
<pre><code>## [1] -0.1750449</code></pre>
<p>So, looking at these correlations there seems to be some relationship between our explanatory (independent) variables and our dependent variables. It is time to form a hypothesis: LSOAs that are in a less deprived IMD decile, LSOAs with a lower mean distance to one of our outlets of interest, and LSOAs that are closer to a tube station, experience more bike theft. The null hypothesis then becomes: this relationship <strong>does not</strong> exist.</p>
<p>Let’s see if we can test this hypothesis using an Ordinary Least Squares (OLS) regression model. In R, models are typically fitted by calling a model-fitting function, in our case <code>lm()</code> (linear model). The <code>lm()</code> function returns a fitted model which we can inspect by calling <code>summary()</code> on the object.</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="exploratory-spatial-data-analysis.html#cb150-1" aria-hidden="true"></a><span class="co"># linear model</span></span>
<span id="cb150-2"><a href="exploratory-spatial-data-analysis.html#cb150-2" aria-hidden="true"></a>crime_model &lt;-<span class="st"> </span><span class="kw">lm</span>(n_crime_cube <span class="op">~</span><span class="st"> </span>imd_dec <span class="op">+</span><span class="st"> </span>gamb_dist <span class="op">+</span><span class="st"> </span>pubs_dist <span class="op">+</span><span class="st"> </span>off_dist <span class="op">+</span><span class="st"> </span>tube_dist, <span class="dt">data=</span>lsoa_join)</span>
<span id="cb150-3"><a href="exploratory-spatial-data-analysis.html#cb150-3" aria-hidden="true"></a></span>
<span id="cb150-4"><a href="exploratory-spatial-data-analysis.html#cb150-4" aria-hidden="true"></a><span class="co"># get the results</span></span>
<span id="cb150-5"><a href="exploratory-spatial-data-analysis.html#cb150-5" aria-hidden="true"></a><span class="kw">summary</span>(crime_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = n_crime_cube ~ imd_dec + gamb_dist + pubs_dist + 
##     off_dist + tube_dist, data = lsoa_join)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.1400 -0.4691 -0.0322  0.4464  4.0813 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  2.4663553  0.0894498  27.573  &lt; 2e-16 ***
## imd_dec      0.0257697  0.0126189   2.042   0.0414 *  
## gamb_dist   -0.2611631  0.1194108  -2.187   0.0290 *  
## pubs_dist   -1.3719555  0.1489382  -9.212  &lt; 2e-16 ***
## off_dist    -0.0100393  0.0831764  -0.121   0.9040    
## tube_dist   -0.0005161  0.0001010  -5.109 3.86e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.8039 on 1014 degrees of freedom
## Multiple R-squared:  0.2034,	Adjusted R-squared:  0.1995 
## F-statistic: 51.79 on 5 and 1014 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>In running a regression model, we are effectively trying to test our null hypothesis. If our null hypothesis is true then we expect our coefficients to equal to 0. Right now our null hypothesis is that there is no relationship between bike theft and our input variables. Without going in much further detail, as this will be in-depth covered in your <a href="https://andrewmaclachlan.github.io/CASA0005repo/gwr-and-spatially-lagged-regression.html">CASA005 module</a>, we can see that the null hypothesis is disproven and, in fact, there seems to be a negative relationship between our distance-related input variables and our dependent variable. Four out of our five variables are significant at a 0.05 level of significance. The R-squared, which is a measure of the goodness-of-fit of the model, suggest that <strong>19.95</strong> per cent of the variation in our dependent variable can be explained by our independent variables. This means that a relationship is present, but it is not very strong! Nonetheless, the model suggest that LSOAs with a higher IMD score, a higher accessibility to pubs, a higher accessibility to gambling outlets, and a higher accessibility to a tube location, experience more bike theft. Consider that when parking your bike somewhere overnight.</p>
</div>
<div id="important" class="section level4 unnumbered">
<h4>Important</h4>
<p>Normally, you would also check the underlying assumptions of the linear model (linearity, homoscedasticity, independence, and normality), however, this will be covered more in-depth in your <a href="https://andrewmaclachlan.github.io/CASA0005repo/gwr-and-spatially-lagged-regression.html">CASA005 module</a> and for our current purposes we are going to be a little naughty and accept the results as is and assume that all our underlying assumptions are satisfied (even though we are actually violating some of these underlying assumptions!).</p>
<p>If you do want to get into some more detail on regression analysis right here and now, the following video explains the process of fitting a line to your data very clearly. While you at it, do have a look at some of the other videos on the <a href="https://www.youtube.com/channel/UCtYLUTtgS3k1Fg4y5tAhLbw">StatsQuestwith Josh Stammer</a> Youtube Channel.</p>
<div class="vembedr" align="left">
<div>
<iframe src="https://www.youtube.com/embed/nk2CQITm_eo" width="533" height="300" frameborder="1" allowfullscreen=""></iframe>
</div>
</div>
</div>
</div>
</div>
<div id="spatial-heterogeneity" class="section level2" number="5.4">
<h2><span class="header-section-number">5.4</span> Spatial heterogeneity</h2>
<p>We now have established a relationship between IMD deciles, access to gambling outlets, access to pubs, access to off licenses, access to the nearest tube stations, and the occurrence of bike theft. However, our data are very spatial and we did not incorporate this spatial distribution into our model. So if we want to develop a regression model for bike theft in London we may have to recognise this spatial component. On top of this, a regression model assumes independence of observations: what happens in LSOA001 is not related to what happens in LSOA002 or any other LSOA. However, we know from last weeks content that this is not always the case because of spatial autocorrelation.</p>
<div id="video-spatial-heterogeneity" class="section level3" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> Video: Spatial heterogeneity</h3>
<p><div class="vembedr" align="left">
<div>
<iframe src="https://web.microsoftstream.com/embed/video/454ff23d-4d5c-4ae4-9f3c-323a71c42b67?autoplay=false&amp;showinfo=true" width="533" height="300" style="border:none;"></iframe>
</div>
</div>
<a href="https://github.com/jtvandijk/GEOG0114/tree/master/slides/w05/w05_03_spatial_models.pdf">[Lecture slides]</a> <a href="https://web.microsoftstream.com/video/454ff23d-4d5c-4ae4-9f3c-323a71c42b67?list=studio">[Watch on MS stream]</a></p>
</div>
<div id="example-accounting-for-spatial-heterogeneity" class="section level3" number="5.4.2">
<h3><span class="header-section-number">5.4.2</span> Example: Accounting for spatial heterogeneity</h3>
<p>Let’s start by exploring wether autocorrelation is an issue in our current analysis. Make sure the following libraries are loaded:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="exploratory-spatial-data-analysis.html#cb152-1" aria-hidden="true"></a><span class="co"># load libraries</span></span>
<span id="cb152-2"><a href="exploratory-spatial-data-analysis.html#cb152-2" aria-hidden="true"></a><span class="kw">library</span>(sf)</span>
<span id="cb152-3"><a href="exploratory-spatial-data-analysis.html#cb152-3" aria-hidden="true"></a><span class="kw">library</span>(tmap)</span>
<span id="cb152-4"><a href="exploratory-spatial-data-analysis.html#cb152-4" aria-hidden="true"></a><span class="kw">library</span>(sp)</span>
<span id="cb152-5"><a href="exploratory-spatial-data-analysis.html#cb152-5" aria-hidden="true"></a><span class="kw">library</span>(spdep)</span>
<span id="cb152-6"><a href="exploratory-spatial-data-analysis.html#cb152-6" aria-hidden="true"></a><span class="kw">library</span>(spatialreg)</span></code></pre></div>
<p>Now we are ready to go again, we are going to start by having a closer look at the residuals of our model. In other words, the residuals represent the distance between the observed values of the dependent variable and the predicted values of our dependent variables in our linear model. Residuals should be randomly distributed over space, otherwise we may be dealing with spatial autocorrelation. Strange words coming from a geographer, but right now we do <strong>not</strong> want to see any spatial patterning.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="exploratory-spatial-data-analysis.html#cb153-1" aria-hidden="true"></a><span class="co"># extract the residuals from the model and assign to our spatial dataset</span></span>
<span id="cb153-2"><a href="exploratory-spatial-data-analysis.html#cb153-2" aria-hidden="true"></a>lsoa_join<span class="op">$</span>residuals &lt;-<span class="st"> </span><span class="kw">residuals</span>(crime_model)</span>
<span id="cb153-3"><a href="exploratory-spatial-data-analysis.html#cb153-3" aria-hidden="true"></a></span>
<span id="cb153-4"><a href="exploratory-spatial-data-analysis.html#cb153-4" aria-hidden="true"></a><span class="co"># extract the predicted values from the model and assign to our spatial dataset</span></span>
<span id="cb153-5"><a href="exploratory-spatial-data-analysis.html#cb153-5" aria-hidden="true"></a>lsoa_join<span class="op">$</span>predicted &lt;-<span class="st"> </span><span class="kw">fitted</span>(crime_model)</span>
<span id="cb153-6"><a href="exploratory-spatial-data-analysis.html#cb153-6" aria-hidden="true"></a></span>
<span id="cb153-7"><a href="exploratory-spatial-data-analysis.html#cb153-7" aria-hidden="true"></a><span class="co"># example observed, residual, predicted of first LSOA in our data</span></span>
<span id="cb153-8"><a href="exploratory-spatial-data-analysis.html#cb153-8" aria-hidden="true"></a>lsoa_join[<span class="dv">1</span>,<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">9</span>,<span class="dv">11</span>,<span class="dv">12</span>)]</span></code></pre></div>
<pre><code>## Simple feature collection with 1 feature and 4 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: 528983.6 ymin: 177857 xmax: 529243.5 ymax: 178173.5
## CRS:            27700
##    lsoa11cd n_crime_cube  residuals predicted                       geometry
## 1 E01004665     1.587401 -0.2261528  1.813554 MULTIPOLYGON (((529040.9 17...</code></pre>
<p>Now we have our residuals assigned to their spatial units, we can plot the residuals in number of standard deviations from the mean.</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="exploratory-spatial-data-analysis.html#cb155-1" aria-hidden="true"></a><span class="co"># standardise</span></span>
<span id="cb155-2"><a href="exploratory-spatial-data-analysis.html#cb155-2" aria-hidden="true"></a>lsoa_join<span class="op">$</span>sd_mean &lt;-<span class="st"> </span>(lsoa_join<span class="op">$</span>predicted <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(lsoa_join<span class="op">$</span>predicted)) <span class="op">/</span><span class="st"> </span><span class="kw">sd</span>(lsoa_join<span class="op">$</span>predicted)</span>
<span id="cb155-3"><a href="exploratory-spatial-data-analysis.html#cb155-3" aria-hidden="true"></a></span>
<span id="cb155-4"><a href="exploratory-spatial-data-analysis.html#cb155-4" aria-hidden="true"></a><span class="co"># inspect the result</span></span>
<span id="cb155-5"><a href="exploratory-spatial-data-analysis.html#cb155-5" aria-hidden="true"></a>breaks &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="dv">14</span>,<span class="op">-</span><span class="dv">3</span>,<span class="op">-</span><span class="dv">2</span>,<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">14</span>)</span>
<span id="cb155-6"><a href="exploratory-spatial-data-analysis.html#cb155-6" aria-hidden="true"></a><span class="kw">tm_shape</span>(lsoa_join) <span class="op">+</span><span class="st"> </span></span>
<span id="cb155-7"><a href="exploratory-spatial-data-analysis.html#cb155-7" aria-hidden="true"></a><span class="st">  </span><span class="kw">tm_fill</span>(<span class="st">&#39;sd_mean&#39;</span>, <span class="dt">style=</span><span class="st">&#39;fixed&#39;</span>, <span class="dt">breaks=</span>breaks, <span class="dt">palette=</span><span class="st">&#39;-RdBu&#39;</span>) <span class="op">+</span></span>
<span id="cb155-8"><a href="exploratory-spatial-data-analysis.html#cb155-8" aria-hidden="true"></a><span class="st">  </span><span class="kw">tm_borders</span>(<span class="dt">alpha =</span> <span class="fl">0.1</span>) </span></code></pre></div>
<p><img src="GEOG0114_files/figure-html/05-standardise-and-plot-yeah-1.png" width="672" /></p>
<p>You can see the spatial patterning of areas of over-prediction in the centre of Greater London with areas of under-prediction concentrating on the edges of the study area. We could be dealing with some spatial autocorrelation, so we need to test for it again. We will be using a Global Moran’s I for this. Remember with a global Moran’s I we can test how ‘random’ the spatial distribution of these values is. Global Moran’s I is a metric between -1 and 1. -1 is a completely even spatial distribution of values, 0 is a ‘random’ distribution, and 1 is a ‘non-random’ distribution of clearly defined clusters.</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="exploratory-spatial-data-analysis.html#cb156-1" aria-hidden="true"></a><span class="co"># force sf to sp</span></span>
<span id="cb156-2"><a href="exploratory-spatial-data-analysis.html#cb156-2" aria-hidden="true"></a>lsoa_join_sp &lt;-<span class="st"> </span><span class="kw">as_Spatial</span>(lsoa_join, <span class="dt">IDs=</span>lsoa_join<span class="op">$</span>lsoa11cd)</span>
<span id="cb156-3"><a href="exploratory-spatial-data-analysis.html#cb156-3" aria-hidden="true"></a></span>
<span id="cb156-4"><a href="exploratory-spatial-data-analysis.html#cb156-4" aria-hidden="true"></a><span class="co"># create a list of neighbours using the &#39;queen&#39; criteria</span></span>
<span id="cb156-5"><a href="exploratory-spatial-data-analysis.html#cb156-5" aria-hidden="true"></a>lsoa_nb &lt;-<span class="st"> </span><span class="kw">poly2nb</span>(lsoa_join_sp, <span class="dt">row.names=</span>lsoa_join_sp<span class="op">$</span>lsoa11cd, <span class="dt">queen=</span><span class="ot">TRUE</span>)</span>
<span id="cb156-6"><a href="exploratory-spatial-data-analysis.html#cb156-6" aria-hidden="true"></a></span>
<span id="cb156-7"><a href="exploratory-spatial-data-analysis.html#cb156-7" aria-hidden="true"></a><span class="co"># check neighbours</span></span>
<span id="cb156-8"><a href="exploratory-spatial-data-analysis.html#cb156-8" aria-hidden="true"></a><span class="kw">summary</span>(lsoa_nb)</span></code></pre></div>
<pre><code>## Neighbour list object:
## Number of regions: 1020 
## Number of nonzero links: 5800 
## Percentage nonzero weights: 0.5574779 
## Average number of links: 5.686275 
## Link number distribution:
## 
##   2   3   4   5   6   7   8   9  10  11  12  13 
##  14  64 152 259 244 166  66  39  10   2   2   2 
## 14 least connected regions:
## E01001823 E01004720 E01004677 E01003143 E01033596 E01033710 E01004692 E01004218 E01003030 E01003142 E01001813 E01032775 E01004739 E01004732 with 2 links
## 2 most connected regions:
## E01000946 E01000953 with 13 links</code></pre>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="exploratory-spatial-data-analysis.html#cb158-1" aria-hidden="true"></a><span class="co"># generate the row standardised spatial weight matrix</span></span>
<span id="cb158-2"><a href="exploratory-spatial-data-analysis.html#cb158-2" aria-hidden="true"></a>wm &lt;-<span class="st"> </span><span class="kw">nb2mat</span>(lsoa_nb, <span class="dt">style=</span><span class="st">&#39;B&#39;</span>)</span>
<span id="cb158-3"><a href="exploratory-spatial-data-analysis.html#cb158-3" aria-hidden="true"></a>rwm &lt;-<span class="st"> </span><span class="kw">nb2listw</span>(lsoa_nb, <span class="dt">style=</span><span class="st">&#39;W&#39;</span>)</span></code></pre></div>
<p>Now we can execute a Moran’s test <strong>for the regression residuals</strong>. We use <code>lm.morantest()</code> for this. This is important because this function takes into account that the input data are residuals, something which the ‘normal’ Moran’s I test does not do.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="exploratory-spatial-data-analysis.html#cb159-1" aria-hidden="true"></a><span class="co"># Moran&#39;s I</span></span>
<span id="cb159-2"><a href="exploratory-spatial-data-analysis.html#cb159-2" aria-hidden="true"></a><span class="kw">lm.morantest</span>(crime_model, rwm, <span class="dt">alternative=</span><span class="st">&#39;two.sided&#39;</span>)</span></code></pre></div>
<pre><code>## 
## 	Global Moran I for regression residuals
## 
## data:  
## model: lm(formula = n_crime_cube ~ imd_dec + gamb_dist + pubs_dist +
## off_dist + tube_dist, data = lsoa_join)
## weights: rwm
## 
## Moran I statistic standard deviate = 18.427, p-value &lt; 2.2e-16
## alternative hypothesis: two.sided
## sample estimates:
## Observed Moran I      Expectation         Variance 
##     0.3439158982    -0.0035656704     0.0003556032</code></pre>
<p>Not surprisingly, the test is significant: we are indeed dealing with spatial autocorrelation. This means that our OLS regression may not be the best way to respresent our data as currently our regression line will per definition under-predict or over-predict in areas that are close to one another. There are two ways of taking this spatial dependence into account: by means of a <strong>spatial error</strong> model or by means of a <strong>spatially lagged</strong> model. These methods are quite different as they treat spatial autocorrelation in different ways. In the first case, the observed spatial dependence <em>is not</em> considered as an actual spatial process but is an effect of spatial clustering. In the second case, spatial dependence <em>is</em> considered as an actual spatial process and ‘space’ should be incorporated as an explanation in the model.</p>
<p>How do we now decide which model to use? Well, first, as with any model, the relationship between independent and dependent variables must make sense. So, for instance, if you think that the spatial dependence is just an artefact of the data distribution rather than a truly spatial process, you should go with a spatial error model. Vice versa, if you think that the spatial dependence is the result of a spatial process, you should consider the spatially lagged model. In less clear cut cases, we can also get a little help by making use of the <strong>Lagrange Multiplier test statistics</strong>. We can these run these tests as follows:</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="exploratory-spatial-data-analysis.html#cb161-1" aria-hidden="true"></a><span class="co"># lagrange mulitplier</span></span>
<span id="cb161-2"><a href="exploratory-spatial-data-analysis.html#cb161-2" aria-hidden="true"></a><span class="kw">lm.LMtests</span>(crime_model, rwm, <span class="dt">test =</span> <span class="kw">c</span>(<span class="st">&#39;LMerr&#39;</span>,<span class="st">&#39;LMlag&#39;</span>,<span class="st">&#39;RLMerr&#39;</span>,<span class="st">&#39;RLMlag&#39;</span>))</span></code></pre></div>
<pre><code>## 
## 	Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = n_crime_cube ~ imd_dec + gamb_dist + pubs_dist +
## off_dist + tube_dist, data = lsoa_join)
## weights: rwm
## 
## LMerr = 327.63, df = 1, p-value &lt; 2.2e-16
## 
## 
## 	Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = n_crime_cube ~ imd_dec + gamb_dist + pubs_dist +
## off_dist + tube_dist, data = lsoa_join)
## weights: rwm
## 
## LMlag = 355.85, df = 1, p-value &lt; 2.2e-16
## 
## 
## 	Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = n_crime_cube ~ imd_dec + gamb_dist + pubs_dist +
## off_dist + tube_dist, data = lsoa_join)
## weights: rwm
## 
## RLMerr = 1.1286, df = 1, p-value = 0.2881
## 
## 
## 	Lagrange multiplier diagnostics for spatial dependence
## 
## data:  
## model: lm(formula = n_crime_cube ~ imd_dec + gamb_dist + pubs_dist +
## off_dist + tube_dist, data = lsoa_join)
## weights: rwm
## 
## RLMlag = 29.348, df = 1, p-value = 6.049e-08</code></pre>
<p>How dow we use this information? The output of the test is split into two groups: the standard tests (<strong>LMerr</strong> and <strong>LMlag</strong>) and the robust versions of these tests (<strong>RLMerr</strong> and <strong>RMlag</strong>).</p>
<p>The robust version should be used only if both of the standard tests are significant (i.e. below the .05 level). If only one of the standard tests comes back signficant, but the other one is not, then it becomes very easy to decide between the spatial error and the spatially lagged model: choose the one that is significant! In case both the standard tests are significant we would need to look at the outcomes of the robust tests and make a decision. In such a situation, the best suggestion is to compare the <em>p-values</em> of both tests and select the model that is ‘more significant’ than the other. In our case the situation is very clear and we should go with a spatially lagged model rather than a spatial error model. Let’s do that using the <code>lagsarlm()</code> function. Also, let’s remove the distance to the neareast off license as that variable was not significant to begin with.</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="exploratory-spatial-data-analysis.html#cb163-1" aria-hidden="true"></a><span class="co"># execute the spatially lagged model</span></span>
<span id="cb163-2"><a href="exploratory-spatial-data-analysis.html#cb163-2" aria-hidden="true"></a><span class="co"># this can take a little bit of time, be patient!</span></span>
<span id="cb163-3"><a href="exploratory-spatial-data-analysis.html#cb163-3" aria-hidden="true"></a>crime_model_lag &lt;-<span class="st"> </span><span class="kw">lagsarlm</span>(n_crime_cube <span class="op">~</span><span class="st"> </span>imd_dec <span class="op">+</span><span class="st"> </span>pubs_dist <span class="op">+</span><span class="st"> </span>gamb_dist <span class="op">+</span><span class="st"> </span>tube_dist, <span class="dt">data=</span>lsoa_join, <span class="dt">listw=</span>rwm)</span>
<span id="cb163-4"><a href="exploratory-spatial-data-analysis.html#cb163-4" aria-hidden="true"></a></span>
<span id="cb163-5"><a href="exploratory-spatial-data-analysis.html#cb163-5" aria-hidden="true"></a><span class="co"># let&#39;s inspet the results</span></span>
<span id="cb163-6"><a href="exploratory-spatial-data-analysis.html#cb163-6" aria-hidden="true"></a><span class="kw">summary</span>(crime_model_lag)</span></code></pre></div>
<pre><code>## 
## Call:lagsarlm(formula = n_crime_cube ~ imd_dec + pubs_dist + gamb_dist + 
##     tube_dist, data = lsoa_join, listw = rwm)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -2.202012 -0.393879  0.016251  0.403836  3.178825 
## 
## Type: lag 
## Coefficients: (asymptotic standard errors) 
##                Estimate  Std. Error z value  Pr(&gt;|z|)
## (Intercept)  1.12440760  0.09842553 11.4239 &lt; 2.2e-16
## imd_dec      0.03119665  0.01078435  2.8928 0.0038186
## pubs_dist   -0.77701415  0.12727377 -6.1051 1.028e-09
## gamb_dist   -0.16495609  0.09942310 -1.6591 0.0970891
## tube_dist   -0.00031330  0.00008769 -3.5729 0.0003531
## 
## Rho: 0.54502, LR test value: 244.87, p-value: &lt; 2.22e-16
## Asymptotic standard error: 0.033565
##     z-value: 16.238, p-value: &lt; 2.22e-16
## Wald statistic: 263.67, p-value: &lt; 2.22e-16
## 
## Log likelihood: -1099.293 for lag model
## ML residual variance (sigma squared): 0.47432, (sigma: 0.68871)
## Number of observations: 1020 
## Number of parameters estimated: 7 
## AIC: 2212.6, (AIC for lm: 2455.5)
## LM test for residual autocorrelation
## test value: 8.1292, p-value: 0.0043559</code></pre>
<p>To interpret these results, we have to look at the Akaike Information Criterion (AIC). The AIC of our spatially lagged model is 2212.6, whereas the model without taking spatial dependence into account has an AIC of 2455.5 This means that the spatially lagged model is a better fit to the data then the standard OLS model. We also have a new term <strong>Rho</strong>, which is the spatial autoregressive parameter. In our case it is both positive and statistically significant, suggesting that when bike theft in the neighbours of area <strong>X</strong><em>i</em> increase, bike theft will also be higher in area <strong>X</strong><em>i</em>. At the same time, the IMD decile, the distance to the nearest pub, and the distance to the nearest tube stations are all still significant. Next time you know where not to park your bike.</p>
<blockquote>
<p>Be careful <strong>not</strong> to compare the regression coefficients of the spatially lagged model to the regression coefficients of the original OLS model because their meaning now has changed. Whilst in the OLS model the coefficient of any of the independent variables measures the overall impact of these variables, this is not the case in the spatially lagged model: by including the spatial lag, the effect that X has on Y depends also (indirectly) on the effect that X has on Y in its neighbours.</p>
</blockquote>
<p>Although we probably should not, let’s also run a spatial error model. Just for the sake of running it and see how it looks.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="exploratory-spatial-data-analysis.html#cb165-1" aria-hidden="true"></a><span class="co"># execute the spatially lagged model</span></span>
<span id="cb165-2"><a href="exploratory-spatial-data-analysis.html#cb165-2" aria-hidden="true"></a><span class="co"># this can take a little bit of time, be patient!</span></span>
<span id="cb165-3"><a href="exploratory-spatial-data-analysis.html#cb165-3" aria-hidden="true"></a>crime_model_err &lt;-<span class="st"> </span><span class="kw">errorsarlm</span>(n_crime_cube <span class="op">~</span><span class="st"> </span>imd_dec <span class="op">+</span><span class="st"> </span>pubs_dist <span class="op">+</span><span class="st"> </span>gamb_dist <span class="op">+</span><span class="st"> </span>tube_dist, <span class="dt">data=</span>lsoa_join, <span class="dt">listw=</span>rwm)</span>
<span id="cb165-4"><a href="exploratory-spatial-data-analysis.html#cb165-4" aria-hidden="true"></a></span>
<span id="cb165-5"><a href="exploratory-spatial-data-analysis.html#cb165-5" aria-hidden="true"></a><span class="co"># let&#39;s inspect the results</span></span>
<span id="cb165-6"><a href="exploratory-spatial-data-analysis.html#cb165-6" aria-hidden="true"></a><span class="kw">summary</span>(crime_model_err)</span></code></pre></div>
<pre><code>## 
## Call:errorsarlm(formula = n_crime_cube ~ imd_dec + pubs_dist + gamb_dist + 
##     tube_dist, data = lsoa_join, listw = rwm)
## 
## Residuals:
##         Min          1Q      Median          3Q         Max 
## -2.1086e+00 -3.8717e-01  5.2999e-05  4.0082e-01  3.1615e+00 
## 
## Type: error 
## Coefficients: (asymptotic standard errors) 
##                Estimate  Std. Error z value  Pr(&gt;|z|)
## (Intercept)  2.01465810  0.10346058 19.4727 &lt; 2.2e-16
## imd_dec      0.06067673  0.01345733  4.5088 6.519e-06
## pubs_dist   -0.96803178  0.15645501 -6.1873 6.121e-10
## gamb_dist   -0.14677894  0.11902951 -1.2331    0.2175
## tube_dist   -0.00049008  0.00012571 -3.8986 9.675e-05
## 
## Lambda: 0.58216, LR test value: 241.97, p-value: &lt; 2.22e-16
## Asymptotic standard error: 0.033829
##     z-value: 17.209, p-value: &lt; 2.22e-16
## Wald statistic: 296.16, p-value: &lt; 2.22e-16
## 
## Log likelihood: -1100.746 for error model
## ML residual variance (sigma squared): 0.47069, (sigma: 0.68607)
## Number of observations: 1020 
## Number of parameters estimated: 7 
## AIC: 2215.5, (AIC for lm: 2455.5)</code></pre>
<p>If we have good reasons to believe that we need to run a spatial error model rather than an OLS regression model, we actually notice that the model fit improves: the AIC of the spatial error model is 2215.5, whilst the AIC of the OLS model is still 2455.5 Keep in mind: whereas the spatially lagged model takes spatial dependence into account, the spatial error model simply tries to remove the influence of space and we in fact estimate a model that relaxes one of the standard regression model assumptions that the errors need to be independent.</p>
<blockquote>
<p>This time you could actually compare the regression coefficients from the spatial error model with those from the OLS model!</p>
</blockquote>
</div>
<div id="geographically-weighted-regression" class="section level3 unnumbered">
<h3>Geographically Weighted Regression</h3>
<p>As mentioned in the short lecture video, another option to take ‘space’ into account is by executing a Geographically Weighted Regression (GWR). However, as this week’s content is already getting very long as well as that GWR will be covered in your <a href="https://andrewmaclachlan.github.io/CASA0005repo/gwr-and-spatially-lagged-regression.html">CASA005 module</a>, we will not cover this now. Do have a look at the article by <a href="https://onlinelibrary.wiley.com/doi/10.1111/gean.12259">Shabrian et al. 2020</a> that is part of this week’s essential reading to see GWR in action.</p>
</div>
</div>
<div id="take-home-message" class="section level2" number="5.5">
<h2><span class="header-section-number">5.5</span> Take home message</h2>
<p>Exploratory (Spatial) Data Analysis is at the core of any analysis. After you cleaned and prepared your data, you first want to inspect your data through simple and visual methods to get acquainted with the data. Then you can start looking for relationships, and, if any relationships are found you are going to want to ask the question to what extent these relationships are real or to what extent other (spatial) processes, such as spatial dependence, play a role in shaping these relationships. That is it for this week! Next week we will move to point pattern analysis, but that is next week so for now we can <a href="https://www.youtube.com/watch?v=d8Fmu3RLEOY">celebrate the successful completion</a> of this week’s material.</p>
</div>
<div id="attributions_w05" class="section level2" number="5.6">
<h2><span class="header-section-number">5.6</span> Attributions</h2>
<p>This week’s content and practical uses content and inspiration from:</p>
<ul>
<li>Wickham, H., Grolemund, G. 2017. R for Data Science. <a href="https://r4ds.had.co.nz/index.html" class="uri">https://r4ds.had.co.nz/index.html</a></li>
<li>Medina, J, Solymosi, R. 2019. Crime Mapping in R. <a href="https://maczokni.github.io/crimemapping_textbook_bookdown/" class="uri">https://maczokni.github.io/crimemapping_textbook_bookdown/</a></li>
</ul>
</div>
<div id="feedback_w05" class="section level2" number="5.7">
<h2><span class="header-section-number">5.7</span> Feedback</h2>
<p>Please take a moment to give us some <a href="https://forms.gle/BYbZySVSHeoUEkJh9">feedback on this week’s content</a>.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="spatial-autocorrelation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="point-pattern-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/jtvandijk/GEOG0114/edit/master/05-week05.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["https://github.com/jtvandijk/GEOG0114/raw/master/05-week05.Rmd"],
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
